# Configuration for rlvgl-chips-nrf crate.
[package]
name = "rlvgl-chips-nrf"
version = "0.0.2"
authors = ["Ira Abbott <ira@softoboros.com>"]
edition = "2021"
license = "MIT"
description = "Nordic chip database adapter for rlvgl code generation."
publish = true
readme = "README.md"
repository = "https://github.com/softoboros/rlvgl"
homepage = "https://github.com/softoboros/rlvgl"
documentation = "https://docs.rs/rlvgl-chips-nrf"
keywords = ["embedded", "nordic", "nrf", "mcu", "no_std"]
categories = ["config", "embedded"]

[lib]
crate-type = ["rlib"]

[dependencies]
serde = { version = "1", features = ["derive"], optional = true }
