[package]
name = "rlvgl"
version = "0.1.0"
authors = ["Ira Abbott <ira@softobotos.com>"]
edition = "2024"
license = "MIT"
description = "A modular, idiomatic Rust reimplementation of the LVGL graphics library for embedded and simulator use."
readme = "README.md"
repository = "https://github.com/softoboros/rlvgl"
homepage = "https://github.com/softoboros/rlvgl"
documentation = "https://docs.rs/rlvgl"
keywords = ["embedded", "graphics", "ui", "lvgl", "no_std"]
categories = ["embedded", "gui", "no-std", "graphics"]
publish = true
exclude = [
  "lvgl/**",
  "docs/**",
  "examples/**",
  ".github/**",
  "scripts/**",
  "target/**"
]

[lib]
path = "src/lib.rs"

[dependencies]
rlvgl-core = { version = "0.1.0", path = "core", default-features = false }
rlvgl-widgets = { version = "0.1.1", path = "widgets", default-features = false }
rlvgl-platform = { version = "0.1.0", path = "platform", default-features = false }

[dependencies.gif]
version = "*"
optional = true
[dependencies.fontdue]
version = "*"
optional = true
[dependencies.dotlottie-rs]
version = "0.1.0-alpha.1"
optional = true
[dependencies.embedded-canvas]
version = "0.3.1"
optional = true
[dependencies.embedded-graphics]
version = "0.8"
optional = true
[dependencies.pinyin]
version = "*"
optional = true
[dependencies.fatfs]
version = "0.3"
optional = true
[dependencies.fscommon]
version = "0.1"
optional = true
[dependencies.yane]
version = "1"
default-features = false
optional = true

[features]
default = []
png = ["rlvgl-core/png"]
jpeg = ["rlvgl-core/jpeg"]
gif = ["rlvgl-core/gif", "dep:gif"]
qrcode = ["rlvgl-core/qrcode"]
simulator = ["rlvgl-platform/simulator"]
st7789 = ["rlvgl-platform/st7789"]
fontdue = ["rlvgl-core/fontdue", "dep:fontdue"]
lottie = ["rlvgl-core/lottie", "dep:dotlottie-rs"]
canvas = ["rlvgl-core/canvas", "dep:embedded-canvas", "dep:embedded-graphics"]
pinyin = ["rlvgl-core/pinyin"]
pinyin = ["rlvgl-core/pinyin", "dep:pinyin"]
fatfs = ["rlvgl-core/fatfs", "dep:fatfs", "dep:fscommon"]
nes = ["rlvgl-core/nes", "dep:yane"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
debug = false
panic = "abort"
strip = true

[profile.dev]
opt-level = 1
debug = true

[workspace]
members = ["core", "platform", "widgets"]
resolver = "2"

