[package]
name = "rlvgl"
version = "0.1.0"
authors = ["Ira Abbott <ira@softobotos.com>"]
edition = "2024"
license = "MIT"
description = "A modular, idiomatic Rust reimplementation of the LVGL graphics library for embedded and simulator use."
readme = "README.md"
repository = "https://github.com/softoboros/rlvgl"
homepage = "https://github.com/softoboros/rlvgl"
documentation = "https://docs.rs/rlvgl"
keywords = ["embedded", "graphics", "ui", "lvgl", "no_std"]
categories = ["embedded", "gui", "no-std", "graphics"]
publish = true

[lib]
path = "src/lib.rs"

[dependencies]
rlvgl-core = { version = "0.1.0", path = "core", default-features = false }
rlvgl-widgets = { version = "0.1.0", path = "widgets", default-features = false }
rlvgl-platform = { version = "0.1.0", path = "platform", default-features = false }

[features]
default = []
png = ["rlvgl-core/png"]
jpeg = ["rlvgl-core/jpeg"]
qrcode = ["rlvgl-core/qrcode"]
simulator = ["rlvgl-platform/simulator"]
st7789 = ["rlvgl-platform/st7789"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
debug = false
panic = "abort"
strip = true

[profile.dev]
opt-level = 1
debug = true

[workspace]
members = ["core", "platform", "widgets"]
resolver = "2"

