//! Auto-generated by rlvgl-creator — DO NOT EDIT
#![no_std]

/// Ergonomic re-exports of the default form.
pub mod prelude {
}

pub mod b_g473e_zest1s;

pub mod b_g474e_dpow1;

pub mod b_l072z_lrwan1;

pub mod b_l462e_cell1;

pub mod b_l475e_iot01a1;

pub mod b_l475e_iot01a2;

pub mod b_l4s5i_iot01a;

pub mod b_u585i_iot02a;

pub mod b_wb1m_wpan1;

pub mod b_wba5m_wpan;

pub mod b_wba6m_wpan;

pub mod b_wl5m_subg1;

pub mod nucleo_c031c6;

pub mod nucleo_c051c8;

pub mod nucleo_c071rb;

pub mod nucleo_c092rc;

pub mod nucleo_f030r8;

pub mod nucleo_f031k6;

pub mod nucleo_f042k6;

pub mod nucleo_f070rb;

pub mod nucleo_f072rb;

pub mod nucleo_f091rc;

pub mod nucleo_f103rb;

pub mod nucleo_f103rb2;

pub mod nucleo_f207zg;

pub mod nucleo_f302r8;

pub mod nucleo_f303k8;

pub mod nucleo_f303re;

pub mod nucleo_f303ze;

pub mod nucleo_f334r8;

pub mod nucleo_f401re;

pub mod nucleo_f401re2;

pub mod nucleo_f410rb;

pub mod nucleo_f411re;

pub mod nucleo_f411re2;

pub mod nucleo_f412zg;

pub mod nucleo_f413zh;

pub mod nucleo_f429zi;

pub mod nucleo_f439zi;

pub mod nucleo_f446re;

pub mod nucleo_f446re2;

pub mod nucleo_f446ze;

pub mod nucleo_f722ze;

pub mod nucleo_f746zg;

pub mod nucleo_f756zg;

pub mod nucleo_f767zi;

pub mod nucleo_g031k8;

pub mod nucleo_g070rb;

pub mod nucleo_g071rb;

pub mod nucleo_g0b1re;

pub mod nucleo_g431kb;

pub mod nucleo_g431rb;

pub mod nucleo_g474re;

pub mod nucleo_g491re;

pub mod nucleo_h503rb;

pub mod nucleo_h533re;

pub mod nucleo_h563zi;

pub mod nucleo_h723zg;

pub mod nucleo_h743zi;

pub mod nucleo_h743zi2;

pub mod nucleo_h745zi_q;

pub mod nucleo_h753zi;

pub mod nucleo_h755zi_q;

pub mod nucleo_h7a3zi_q;

pub mod nucleo_h7s3l8;

pub mod nucleo_l010rb;

pub mod nucleo_l011k4;

pub mod nucleo_l031k6;

pub mod nucleo_l053r8;

pub mod nucleo_l073rz;

pub mod nucleo_l152re;

pub mod nucleo_l412kb;

pub mod nucleo_l412rb_p;

pub mod nucleo_l432kc;

pub mod nucleo_l433rc_p;

pub mod nucleo_l452re;

pub mod nucleo_l452re_p;

pub mod nucleo_l476rg;

pub mod nucleo_l476rg2;

pub mod nucleo_l496zg;

pub mod nucleo_l496zg_p;

pub mod nucleo_l4a6zg;

pub mod nucleo_l4p5zg;

pub mod nucleo_l4r5zi;

pub mod nucleo_l4r5zi_p;

pub mod nucleo_l552ze_q;

pub mod nucleo_n657x0_q;

pub mod nucleo_u031r8;

pub mod nucleo_u083rc;

pub mod nucleo_u385rg_q;

pub mod nucleo_u545re_q;

pub mod nucleo_u575zi_q;

pub mod nucleo_u5a5zj_q;

pub mod nucleo_wb05kz;

pub mod nucleo_wb07cc;

pub mod nucleo_wb09ke;

pub mod nucleo_wb15cc;

pub mod nucleo_wb52vgy;

pub mod nucleo_wb55rg;

pub mod nucleo_wba52cg;

pub mod nucleo_wba55cg;

pub mod nucleo_wba65ri;

pub mod nucleo_wl33cc1;

pub mod nucleo_wl33cc2;

pub mod nucleo_wl55jc1;

pub mod nucleo_wl55jc2;

pub mod p_l496g_cell01;

pub mod p_l496g_cell02;

pub mod p_nucleo_wb55_nucleo;

pub mod p_nucleo_wb55_usbdongle;

pub mod steval_astra1b;

pub mod steval_idp005v1;

pub mod steval_idp005v2;

pub mod steval_mkboxpro;

pub mod steval_mksbox1v1;

pub mod steval_proteus1;

pub mod steval_smartag2;

pub mod steval_stwinbx1;

pub mod steval_stwinkt1;

pub mod steval_stwinkt1b;

pub mod stm320518_eval;

pub mod stm32072b_eval;

pub mod stm32091c_eval;

pub mod stm32100e_eval;

pub mod stm3210c_eval;

pub mod stm3210e_eval;

pub mod stm3220g_eval;

pub mod stm3221g_eval;

pub mod stm32303c_eval;

pub mod stm32303e_eval;

pub mod stm32373c_eval;

pub mod stm3240g_eval;

pub mod stm3241g_eval;

pub mod stm32429i_eval1;

pub mod stm32439i_eval2;

pub mod stm32446e_eval;

pub mod stm32469i_eval;

pub mod stm32479i_eval;

pub mod stm32746g_eval2;

pub mod stm32756g_eval2;

#[cfg(feature = "stm32-c0")]
pub mod stm32c0116_dk;

#[cfg(feature = "stm32-c0")]
pub mod stm32c0316_dk;

#[cfg(feature = "stm32-f0")]
pub mod stm32f0308_disco;

#[cfg(feature = "stm32-f0")]
pub mod stm32f072b_disco;

#[cfg(feature = "stm32-f0")]
pub mod stm32f0discovery;

#[cfg(feature = "stm32-f3")]
pub mod stm32f303c_disc1;

#[cfg(feature = "stm32-f3")]
pub mod stm32f3348_disco;

#[cfg(feature = "stm32-f3")]
pub mod stm32f3discovery;

#[cfg(feature = "stm32-f4")]
pub mod stm32f401c_disco;

#[cfg(feature = "stm32-f4")]
pub mod stm32f407g_disc1;

#[cfg(feature = "stm32-f4")]
pub mod stm32f411e_disco;

#[cfg(feature = "stm32-f4")]
pub mod stm32f412g_disco;

#[cfg(feature = "stm32-f4")]
pub mod stm32f413h_disco;

#[cfg(feature = "stm32-f4")]
pub mod stm32f429i_disc1;

#[cfg(feature = "stm32-f4")]
pub mod stm32f429i_disco;

#[cfg(feature = "stm32-f4")]
pub mod stm32f469i_disco;

#[cfg(feature = "stm32-f4")]
pub mod stm32f4_disco_audiopack;

#[cfg(feature = "stm32-f7")]
pub mod stm32f723e_disco;

#[cfg(feature = "stm32-f7")]
pub mod stm32f7308_dk;

#[cfg(feature = "stm32-f7")]
pub mod stm32f746g_disco;

#[cfg(feature = "stm32-f7")]
pub mod stm32f7508_dk;

#[cfg(feature = "stm32-f7")]
pub mod stm32f769i_disc1;

#[cfg(feature = "stm32-f7")]
pub mod stm32f769i_disco;

#[cfg(feature = "stm32-f7")]
pub mod stm32f769i_eval;

#[cfg(feature = "stm32-f7")]
pub mod stm32f779i_eval;

#[cfg(feature = "stm32-g0")]
pub mod stm32g0316_disco;

#[cfg(feature = "stm32-g0")]
pub mod stm32g071b_disco;

#[cfg(feature = "stm32-g0")]
pub mod stm32g081b_eval;

#[cfg(feature = "stm32-g0")]
pub mod stm32g0c1e_ev;

#[cfg(feature = "stm32-g4")]
pub mod stm32g474e_eval;

#[cfg(feature = "stm32-g4")]
pub mod stm32g474e_eval1;

#[cfg(feature = "stm32-g4")]
pub mod stm32g484e_eval;

#[cfg(feature = "stm32-h5")]
pub mod stm32h573i_dk;

#[cfg(feature = "stm32-h7")]
pub mod stm32h735g_dk;

#[cfg(feature = "stm32-h7")]
pub mod stm32h743i_disco;

#[cfg(feature = "stm32-h7")]
pub mod stm32h743i_eval;

#[cfg(feature = "stm32-h7")]
pub mod stm32h743i_eval2;

#[cfg(feature = "stm32-h7")]
pub mod stm32h745i_disco;

#[cfg(feature = "stm32-h7")]
pub mod stm32h747i_disc1;

#[cfg(feature = "stm32-h7")]
pub mod stm32h747i_disco;

#[cfg(feature = "stm32-h7")]
pub mod stm32h747i_eval;

#[cfg(feature = "stm32-h7")]
pub mod stm32h750b_dk;

#[cfg(feature = "stm32-h7")]
pub mod stm32h753i_eval;

#[cfg(feature = "stm32-h7")]
pub mod stm32h753i_eval2;

#[cfg(feature = "stm32-h7")]
pub mod stm32h757i_eval;

#[cfg(feature = "stm32-h7")]
pub mod stm32h7b3i_dk;

#[cfg(feature = "stm32-h7")]
pub mod stm32h7b3i_eval;

#[cfg(feature = "stm32-h7")]
pub mod stm32h7s78_dk;

#[cfg(feature = "stm32-l0")]
pub mod stm32l0538_disco;

#[cfg(feature = "stm32-l0")]
pub mod stm32l073z_eval;

#[cfg(feature = "stm32-l1")]
pub mod stm32l100c_disco;

#[cfg(feature = "stm32-l1")]
pub mod stm32l152c_disco;

#[cfg(feature = "stm32-l1")]
pub mod stm32l152d_eval;

#[cfg(feature = "stm32-l4")]
pub mod stm32l476g_disco;

#[cfg(feature = "stm32-l4")]
pub mod stm32l476g_eval;

#[cfg(feature = "stm32-l4")]
pub mod stm32l496g_disco;

#[cfg(feature = "stm32-l4")]
pub mod stm32l4p5g_dk;

#[cfg(feature = "stm32-l4")]
pub mod stm32l4r9i_disco;

#[cfg(feature = "stm32-l4")]
pub mod stm32l4r9i_eval;

#[cfg(feature = "stm32-l5")]
pub mod stm32l552e_ev;

#[cfg(feature = "stm32-l5")]
pub mod stm32l562e_dk;

pub mod stm32l_discovery;

pub mod stm32mp135f_dk;

pub mod stm32mp157d_dk1;

pub mod stm32mp157d_ev1;

pub mod stm32mp157f_dk2;

pub mod stm32mp157f_ev1;

pub mod stm32mp215f_dk;

pub mod stm32mp257f_dk;

pub mod stm32mp257f_ev1;

#[cfg(feature = "stm32-n6")]
pub mod stm32n6570_dk;

#[cfg(feature = "stm32-u0")]
pub mod stm32u083c_dk;

#[cfg(feature = "stm32-u5")]
pub mod stm32u575i_ev;

#[cfg(feature = "stm32-u5")]
pub mod stm32u5a9j_dk;

#[cfg(feature = "stm32-u5")]
pub mod stm32u5g9j_dk1;

#[cfg(feature = "stm32-u5")]
pub mod stm32u5g9j_dk2;

pub mod stm32vldiscovery;

pub mod stm32wb5mm_dk;

pub mod stm32wba55g_dk1;

pub mod stm32wba65i_dk1;
