[build]
target = "riscv32imafc-unknown-none-elf"

[target.riscv32imafc-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tmemory.x",
]

[unstable]
build-std = ["core"]
