/* Generated by rlvgl-creator from chipdb/rlvgl-chips-esp/db/chips/esp32_p4.yaml.
 *
 * Linker supplement for ESP32-P4 (rv32imafc). Defines
 * the symbols esp-riscv-rt expects the chip's HAL to provide so that bare
 * raw-PAC examples can link without pulling esp-hal as a dependency.
 *
 * Required by:
 *   - esp-riscv-rt 0.13's _dispatch_exception (calls _start_trap_rust_hal)
 *   - esp-riscv-rt 0.13's _pre_default_start_trap (reads _dram_data_start
 *     for stack-overflow detection)
 *
 * Consumed via the example crate's build.rs as `-Tesp32_p4.x`,
 * sequenced after `-Tmemory.x` and before `-Tlink.x` so REGION_DATA is
 * defined when this file is parsed.
 */

/* Start of writable RAM region — used as the stack-overflow threshold
 * inside esp-riscv-rt's pre-default trap handler. */
PROVIDE(_dram_data_start = ORIGIN(REGION_DATA));

/* Place esp_app_desc_t adjacent to .rodata so both end up in the same
 * r-- LOAD program header. This produces ONE DROM segment in the
 * IDF image format (.app_desc + .rodata combined), matching the
 * canonical IDF layout (compare esp-idf/components/esp_system/ld/
 * esp32p4/sections.ld.in `.flash.appdesc` placement next to
 * `.flash.rodata` in `rodata_seg_low`). The bootloader scans the
 * first DROM segment for magic 0xABCD5432 and refuses to start the
 * app if it's absent. See ERRATA-004 for the layout history. */
SECTIONS
{
    .app_desc : ALIGN(0x10)
    {
        KEEP(*(.app_desc))
        . = ALIGN(0x10);
    } > FLASH_DROM
} INSERT BEFORE .rodata;

/* riscv-rt's link.x doesn't discard .eh_frame; it lands at the same
 * default LMA as .text and collides. Drop it — bare-metal builds don't
 * unwind. */
SECTIONS
{
    /DISCARD/ :
    {
        *(.eh_frame)
        *(.eh_frame_hdr)
    }
}

/* Default Rust-side trap handler. esp-riscv-rt's _dispatch_exception
 * calls this on every unhandled exception. Real HALs override; the
 * default here aborts so the panic handler runs. */
PROVIDE(_start_trap_rust_hal = abort);

/* Default vectored-interrupt dispatcher. esp-riscv-rt's per-interrupt
 * trampolines (`Trap1..Trap31`) load the IRQ number into `a0` and
 * `j handle_interrupts`. Real HALs replace this with a CLINT/PLIC
 * dispatch routine; the default aborts. */
PROVIDE(handle_interrupts = abort);