[package]
name = "rlvgl-example-disco"
version = "0.1.0"
edition = "2024"
publish = false
build = "build.rs"

[[bin]]
name = "rlvgl-stm32h747i-disco"
path = "src/main.rs"
required-features = ["cm7"]

[[bin]]
name = "rlvgl-stm32h747i-disco-cm4"
path = "src/cm4_main.rs"
required-features = ["cm4"]

[features]
default = []
cm7 = [
    "rlvgl-platform/stm32h747i_disco",
    "stm32h7/stm32h747cm7",
    "dep:stm32h7xx-hal",
    "dep:embedded-hal",
    "dep:embedded-hal-02",
    "dep:embedded-sdmmc",
]
cm4 = ["stm32h7/stm32h747cm4"]
splash = ["rlvgl-platform/splash"]
desktop = []
dma2d = ["rlvgl-platform/dma2d"]
cpu_stats = []
audio = ["rlvgl-platform/audio"]
qspi_flash = []
sd_storage = ["rlvgl-platform/sd_storage"]
c_hal = ["dep:rlvgl-bsps-stm", "rlvgl-bsps-stm/c_hal"]
c_hal_cm4 = ["dep:rlvgl-bsps-stm", "rlvgl-bsps-stm/c_hal_cm4"]
pac_sdram_init = []
sdram_ramtest = ["rlvgl-platform/sdram_ramtest"]
hal_sdram = ["dep:stm32-fmc"]
backlight_pwm = []
semihosting = ["dep:cortex-m-semihosting"]
bsp_log = []

[dependencies]
rlvgl-core = { path = "../../core", default-features = false }
rlvgl-platform = { path = "../../platform", default-features = false }
rlvgl-widgets = { path = "../../widgets", default-features = false }
rlvgl-ui = { path = "../../ui", default-features = false }
rlvgl-i18n = { path = "../../i18n" }
rlvgl-app-demo = { path = "../apps/demo", default-features = false, optional = true }
rlvgl-app-disco-demo = { path = "../apps/disco-demo", default-features = false }
rlvgl-decomp = { path = "../../rlvgl-decomp" }
rlvgl-bsps-stm = { path = "../../chips/stm/bsps", optional = true }
cortex-m-rt = "0.7"
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
embedded-alloc = "=0.5.1"
panic-halt = "1"
stm32h7 = { version = "0.15.1", features = ["rt"] }
cortex-m-semihosting = { version = "0.5", optional = true }
critical-section = "1.1.2"

[target.'cfg(any(target_arch = "arm", target_os = "none"))'.dependencies]
stm32h7xx-hal = { version = "0.16", optional = true, features = ["stm32h747cm7", "sdmmc", "fmc", "xspi"] }
embedded-hal = { version = "1", optional = true }
embedded-hal-02 = { package = "embedded-hal", version = "0.2.7", optional = true, features = ["unproven"] }
embedded-sdmmc = { version = "0.9", default-features = false, optional = true }
stm32-fmc = { version = "0.3.2", optional = true }
