/// README.md crawl text (curated for Star Wars opening crawl).
pub static README_CRAWL: &[&str] = &[
    "RLVGL",
    "",
    "Episode I",
    "THE EMBEDDED MENACE",
    "",
    "rlvgl is a modular, idiomatic",
    "Rust reimplementation of LVGL",
    "(Light and Versatile Graphics",
    "Library).",
    "",
    "It preserves the widget-based",
    "UI paradigm while eliminating",
    "unsafe C-style memory management",
    "and global state.",
    "",
    "Structured for no_std environments,",
    "embedded targets like STM32H7,",
    "and simulator backends for rapid",
    "prototyping.",
    "",
    "GOALS",
    "",
    "Preserve LVGL architecture",
    "and layout system",
    "",
    "Replace C memory handling with",
    "idiomatic Rust ownership",
    "",
    "Support embedded display flush",
    "and input via embedded-hal",
    "",
    "Enable widget hierarchy, styles,",
    "and events using Rust traits",
    "",
    "FEATURES",
    "",
    "no_std + allocator support",
    "",
    "Component-based module layout",
    "core, widgets, platform",
    "",
    "Simulatable via std feature flag",
    "",
    "Pluggable display and input",
    "backends",
    "",
    "PROJECT STRUCTURE",
    "",
    "core: Widget base trait, layout,",
    "event dispatch",
    "",
    "widgets: Rust-native LVGL",
    "widget reimplementations",
    "",
    "platform: Display and input",
    "traits with HAL adapters",
    "",
    "ui: Higher-level UI components",
    "",
    "examples: Board demos and",
    "sample applications",
    "",
    "BSP GENERATOR",
    "",
    "rlvgl-creator converts STM32",
    "CubeMX projects into board",
    "support stubs.",
    "",
    "Two-stage pipeline: import",
    "vendor project files, then",
    "generate Rust initialization",
    "code via MiniJinja templates.",
    "",
    "No per-chip tables maintained.",
    "Class-level rules reused across",
    "instances and vendors.",
    "",
    "MIT License",
    "",
    "May the Rust be with you.",
];
