/// README.md crawl text (curated for Star Wars opening crawl).
pub static README_CRAWL: &[&str] = &[
    "RLVGL",
    "",
    "Episode I",
    "THE EMBEDDED MENACE",
    "",
    "A modular, idiomatic Rust",
    "reimplementation of LVGL.",
    "",
    "Preserves the widget-based",
    "UI paradigm while replacing",
    "unsafe C memory management",
    "with Rust ownership.",
    "",
    "Built for no_std, embedded",
    "targets like STM32H7, and",
    "simulator backends.",
    "",
    "GOALS",
    "",
    "Preserve LVGL architecture",
    "and layout system",
    "",
    "Replace C memory handling",
    "with idiomatic Rust",
    "",
    "Support embedded display",
    "and input via embedded-hal",
    "",
    "Enable widget hierarchy,",
    "styles, and events with",
    "Rust traits",
    "",
    "FEATURES",
    "",
    "no_std + allocator support",
    "",
    "Modular workspace crates",
    "for core, widgets, platform,",
    "UI, API, and i18n",
    "",
    "rlvgl-creator for assets,",
    "vendor databases, and",
    "STM32 BSP generation",
    "",
    "DMA2D-assisted rendering",
    "with compositor, dirty",
    "regions, and motion",
    "",
    "Pluggable display and",
    "input backends",
    "",
    "PROJECT STRUCTURE",
    "",
    "core: Widget trait, layout,",
    "event dispatch",
    "",
    "widgets: Rust-native LVGL",
    "widget reimplementations",
    "",
    "platform: Display and input",
    "traits with HAL adapters",
    "",
    "ui: Higher-level components",
    "",
    "api: Shared ABI types for",
    "bindings and coprocessor",
    "",
    "i18n: Compile-time i18n",
    "with runtime locale blobs",
    "",
    "chipdb: Vendor databases",
    "for creator and BSP gen",
    "",
    "examples: Board demos and",
    "sample applications",
    "",
    "BSP GENERATOR",
    "",
    "rlvgl-creator converts",
    "STM32 CubeMX projects into",
    "board support stubs.",
    "",
    "Two-stage pipeline: import",
    "vendor project files, then",
    "generate Rust init code",
    "via MiniJinja templates.",
    "",
    "No per-chip tables kept.",
    "Class-level rules reused",
    "across instances and",
    "vendors.",
    "",
    "WHAT'S NEW IN 0.1.9",
    "",
    "Creator covers import,",
    "board IR, and Rust BSP",
    "rendering with bundled",
    "alternate-function DBs",
    "",
    "STM32H747I-DISCO flagship",
    "demo: DSI display, touch,",
    "SDRAM, audio, DMA2D",
    "",
    "EventWindow, compositor,",
    "motion helpers, and",
    "display-pipeline fixes",
    "",
    "First-class i18n, API,",
    "chip database, and BSP",
    "crates alongside core UI",
    "",
    "MIT License",
    "",
    "May the Rust be with you.",
];
