/* Generated by rlvgl-creator from chipdb/rlvgl-chips-silabs/db/chips/efm32_gg11.yaml.
 *
 * MEMORY block for EFM32GG11 (cortex-m4f). Each region
 * comes from the chip yaml's `memory:` array; sizes are sourced from the
 * EFM32GG11B Family Reference Manual ("Memory System Overview / Memory
 * Map") and the EFM32GG11B820 data sheet Table 2.1.
 *
 * The REGION_ALIAS lines map the chip's regions onto the names that
 * cortex-m-rt's `link.x` consumes (FLASH / RAM are the canonical names;
 * the REGION_TEXT / REGION_DATA / REGION_RODATA aliases are accepted by
 * recent cortex-m-rt link scripts and are harmless on older versions).
 * The alias targets come from the chip yaml's `linker:` section.
 *
 * Frozen by CHIPS-SILABS-05 §5.2: FLASH origin/length and SRAM
 * origin/length for the EFM32GG11B820 SKU are Standards-Action values.
 */

MEMORY
{
  FLASH : ORIGIN = 0x00000000, LENGTH = 0x00200000    /* rx */
  SRAM : ORIGIN = 0x20000000, LENGTH = 0x00080000    /* rwx */
  USERDATA : ORIGIN = 0x0FE00000, LENGTH = 0x00000800    /* rw */
  LOCKBITS : ORIGIN = 0x0FE04000, LENGTH = 0x00000800    /* rw */
  DEVINFO : ORIGIN = 0x0FE08000, LENGTH = 0x00000800    /* r */
}

/* Canonical cortex-m-rt names. */
REGION_ALIAS("FLASH", FLASH);
REGION_ALIAS("RAM",   SRAM);

/* Optional aliases consumed by newer link.x scripts; harmless if unused. */
REGION_ALIAS("REGION_TEXT",   FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA",   SRAM);
REGION_ALIAS("REGION_BSS",    SRAM);
REGION_ALIAS("REGION_HEAP",   SRAM);
REGION_ALIAS("REGION_STACK",  SRAM);