[package]
name = "rlvgl-widgets"
version = "0.2.5"
authors = ["Ira Abbott <ira@softobotos.com>"]
edition = "2024"
license = "MIT"
description = "Built-in widgets for rlvgl."
readme = "README.md"
repository = "https://github.com/softoboros/rlvgl"
homepage = "https://github.com/softoboros/rlvgl"
documentation = "https://docs.rs/rlvgl-widgets"
keywords = ["embedded", "graphics", "ui", "lvgl", "no_std"]
categories = ["embedded", "gui", "no-std", "graphics"]
publish = true

[dependencies]
rlvgl-core = { version = "0.2.4", path = "../core", default-features = false }
rlvgl-platform = { version = "0.2.4", path = "../platform", default-features = false }
rlvgl-audio-meters-core = { version = "0.2.0", path = "../audio-meters-core", default-features = false }
libm = { version = "0.2", default-features = false }

[features]
lpar_arclabel = []

[dev-dependencies]
rand = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
