/* Auto-generated by rlvgl-creator
* SPDX-FileCopyrightText: 2020 STMicroelectronics
* SPDX-FileCopyrightText: 2025 Softoboros Technology, Inc.
* SPDX-License-Identifier: BSD-3-Clause
* Provenance: STM32_open_pin_data (commit <hash>), build <build-hash>.

*/

//! PAC BSP for the generated board.

#![allow(non_snake_case)]
#![allow(clippy::too_many_arguments)]
#![cfg(feature = "spi2")]

use stm32l4::stm32l4 as pac;

/// Enables GPIO clocks required by the generated board.

pub fn enable_gpio_clocks(dp: &pac::Peripherals) {
    const MASK: u32 = (1u32 << 1) | (1u32 << 8);
    dp.RCC
        .ahb2enr
        .modify(|r, w| unsafe { w.bits(r.bits() | MASK) });
}

/// Configures pins using PAC registers.

pub fn configure_pins_pac(dp: &pac::Peripherals) {
    // GPIOB
    dp.GPIOB.pupdr.modify(|r, w| unsafe {
        let mut bits = r.bits();
        let shift = 13 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b00 << shift;
        let shift = 14 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b00 << shift;
        let shift = 15 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b00 << shift;
        w.bits(bits)
    });
    dp.GPIOB.otyper.modify(|r, w| unsafe {
        let mut bits = r.bits();
        bits &= !(1 << 13);
        bits &= !(1 << 14);
        bits &= !(1 << 15);
        w.bits(bits)
    });
    dp.GPIOB.ospeedr.modify(|r, w| unsafe {
        let mut bits = r.bits();
        let shift = 13 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b11 << shift;
        let shift = 14 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b11 << shift;
        let shift = 15 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b11 << shift;
        w.bits(bits)
    });
    dp.GPIOB.afrl.modify(|r, w| unsafe {
        let mut bits = r.bits();
        w.bits(bits)
    });
    dp.GPIOB.afrh.modify(|r, w| unsafe {
        let mut bits = r.bits();
        let afr_shift = (13 % 8) * 4;
        bits &= !(0xF << afr_shift);
        bits |= (0u32 & 0xF) << afr_shift;
        let afr_shift = (14 % 8) * 4;
        bits &= !(0xF << afr_shift);
        bits |= (0u32 & 0xF) << afr_shift;
        let afr_shift = (15 % 8) * 4;
        bits &= !(0xF << afr_shift);
        bits |= (0u32 & 0xF) << afr_shift;
        w.bits(bits)
    });
    dp.GPIOB.moder.modify(|r, w| unsafe {
        let mut bits = r.bits();
        let shift = 13 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b10 << shift;
        let shift = 14 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b10 << shift;
        let shift = 15 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b10 << shift;
        w.bits(bits)
    });

    // GPIOI
    dp.GPIOI.pupdr.modify(|r, w| unsafe {
        let mut bits = r.bits();
        let shift = 0 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b00 << shift;
        w.bits(bits)
    });
    dp.GPIOI.otyper.modify(|r, w| unsafe {
        let mut bits = r.bits();
        bits &= !(1 << 0);
        w.bits(bits)
    });
    dp.GPIOI.ospeedr.modify(|r, w| unsafe {
        let mut bits = r.bits();
        let shift = 0 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b11 << shift;
        w.bits(bits)
    });
    dp.GPIOI.afrl.modify(|r, w| unsafe {
        let mut bits = r.bits();
        w.bits(bits)
    });
    dp.GPIOI.afrh.modify(|r, w| unsafe {
        let mut bits = r.bits();
        let afr_shift = (0 % 8) * 4;
        bits &= !(0xF << afr_shift);
        bits |= (0u32 & 0xF) << afr_shift;
        w.bits(bits)
    });
    dp.GPIOI.moder.modify(|r, w| unsafe {
        let mut bits = r.bits();
        let shift = 0 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b10 << shift;
        w.bits(bits)
    });
}

/// Disables unused peripherals and masks their interrupts.

/// Enables peripheral clocks for the generated board using PAC registers.

pub fn enable_peripherals(_dp: &pac::Peripherals) {}

/// De-initializes board pins to their analog state.

/// De-initializes board peripherals and clocks using PAC registers.

pub fn deinit_board_pac(dp: &pac::Peripherals) {
    // Return pins to analog and remove pulls/open-drain
    let shift = 13 * 2;
    dp.GPIOB.moder.modify(|r, w| unsafe {
        let mut bits = r.bits() & !(0b11 << shift);
        bits |= 0b11 << shift;
        w.bits(bits)
    });
    dp.GPIOB
        .pupdr
        .modify(|r, w| unsafe { w.bits(r.bits() & !(0b11 << shift)) });
    dp.GPIOB
        .otyper
        .modify(|r, w| unsafe { w.bits(r.bits() & !(1 << 13)) });
    let shift = 14 * 2;
    dp.GPIOB.moder.modify(|r, w| unsafe {
        let mut bits = r.bits() & !(0b11 << shift);
        bits |= 0b11 << shift;
        w.bits(bits)
    });
    dp.GPIOB
        .pupdr
        .modify(|r, w| unsafe { w.bits(r.bits() & !(0b11 << shift)) });
    dp.GPIOB
        .otyper
        .modify(|r, w| unsafe { w.bits(r.bits() & !(1 << 14)) });
    let shift = 15 * 2;
    dp.GPIOB.moder.modify(|r, w| unsafe {
        let mut bits = r.bits() & !(0b11 << shift);
        bits |= 0b11 << shift;
        w.bits(bits)
    });
    dp.GPIOB
        .pupdr
        .modify(|r, w| unsafe { w.bits(r.bits() & !(0b11 << shift)) });
    dp.GPIOB
        .otyper
        .modify(|r, w| unsafe { w.bits(r.bits() & !(1 << 15)) });
    let shift = 0 * 2;
    dp.GPIOI.moder.modify(|r, w| unsafe {
        let mut bits = r.bits() & !(0b11 << shift);
        bits |= 0b11 << shift;
        w.bits(bits)
    });
    dp.GPIOI
        .pupdr
        .modify(|r, w| unsafe { w.bits(r.bits() & !(0b11 << shift)) });
    dp.GPIOI
        .otyper
        .modify(|r, w| unsafe { w.bits(r.bits() & !(1 << 0)) });

    // Gate peripheral clocks

    // Disable DMA controllers and mask their interrupts

    // Disable interrupts
    unsafe {
        pac::NVIC::mask(pac::Interrupt::SPI2);
    }
}
