/* Auto-generated by rlvgl-creator
* SPDX-FileCopyrightText: 2020 STMicroelectronics
* SPDX-FileCopyrightText: 2025 Softoboros Technology, Inc.
* SPDX-License-Identifier: BSD-3-Clause
* Provenance: STM32_open_pin_data (commit <hash>), build <build-hash>.

*/

//! HAL BSP for the generated board.

#![allow(non_snake_case)]
#![allow(clippy::too_many_arguments)]
#![cfg(feature = "i2c4")]

use stm32h7xx_hal::{gpio::Speed, gpiof::*, pac, prelude::*};

/// Enables GPIO clocks required by the generated board.

pub fn enable_gpio_clocks(dp: &pac::Peripherals) {
    const MASK: u32 = (1u32 << 5);
    dp.RCC
        .ahb4enr
        .modify(|r, w| unsafe { w.bits(r.bits() | MASK) });
}

/// Configures pins using the HAL API.

pub fn configure_pins_hal(dp: &pac::Peripherals) {
    let gpiof = dp.GPIOF.split();

    // PF14 I2C4_SCL AF0
    let pf14 = gpiof
        .pf14
        .into_alternate_open_drain::<0>()
        .internal_pull_up(true);

    // PF15 I2C4_SDA AF0
    let pf15 = gpiof
        .pf15
        .into_alternate_open_drain::<0>()
        .internal_pull_up(true);
}

/// Enables peripheral clocks for the generated board.

pub fn enable_peripherals(dp: &pac::Peripherals) {}

/// De-initializes board peripherals and clocks.

pub fn deinit_board_hal(dp: &pac::Peripherals) {
    // Return pins to analog and remove pulls/open-drain
    let shift = 14 * 2;
    dp.GPIOF.moder.modify(|r, w| unsafe {
        let mut bits = r.bits() & !(0b11 << shift);
        bits |= 0b11 << shift;
        w.bits(bits)
    });
    dp.GPIOF
        .pupdr
        .modify(|r, w| unsafe { w.bits(r.bits() & !(0b11 << shift)) });
    dp.GPIOF
        .otyper
        .modify(|r, w| unsafe { w.bits(r.bits() & !(1 << 14)) });
    let shift = 15 * 2;
    dp.GPIOF.moder.modify(|r, w| unsafe {
        let mut bits = r.bits() & !(0b11 << shift);
        bits |= 0b11 << shift;
        w.bits(bits)
    });
    dp.GPIOF
        .pupdr
        .modify(|r, w| unsafe { w.bits(r.bits() & !(0b11 << shift)) });
    dp.GPIOF
        .otyper
        .modify(|r, w| unsafe { w.bits(r.bits() & !(1 << 15)) });

    // Gate peripheral clocks

    // Disable DMA controllers and mask their interrupts

    // Disable interrupts
    unsafe {
        pac::NVIC::mask(pac::Interrupt::I2C4_EV);
    }
    unsafe {
        pac::NVIC::mask(pac::Interrupt::I2C4_ER);
    }
}

/// Initializes the board using HAL drivers.

pub fn init_board_hal(dp: pac::Peripherals /*, clocks */) {
    enable_gpio_clocks(&dp);
    configure_pins_hal(&dp);
    enable_peripherals(&dp);
}
