//! Build script for the rlvgl-chips-nxp crate.
//!
//! Scans `db/chips/` and `db/boards/` for YAML files at build time and emits
//! a `generated.rs` into `OUT_DIR` containing two `match`-based lookup
//! functions that return the raw YAML contents via `include_str!`. The
//! crate's `src/lib.rs` pulls this file in with `include!`.
//!
//! An optional `RLVGL_CHIP_SRC` environment variable is still honoured for
//! drop-in overlays of vendor data from outside the crate tree. When set,
//! the overlay YAML files take precedence over the in-tree db for matching
//! names.

use std::{
    env, fs,
    io::Write,
    path::{Path, PathBuf},
};

fn main() {
    println!("cargo:rerun-if-env-changed=RLVGL_CHIP_SRC");
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("generated.rs");

    let mut chips = collect_yaml(&manifest_dir.join("db/chips"));
    let mut boards = collect_yaml(&manifest_dir.join("db/boards"));

    if let Ok(overlay) = env::var("RLVGL_CHIP_SRC") {
        let overlay_dir = PathBuf::from(overlay);
        println!("cargo:rerun-if-changed={}", overlay_dir.display());
        overlay_into(&mut chips, &overlay_dir.join("chips"));
        overlay_into(&mut boards, &overlay_dir.join("boards"));
    }

    let rerun_root = manifest_dir.join("db");
    println!("cargo:rerun-if-changed={}", rerun_root.display());

    let board_infos: Vec<BoardInfoLit> = boards
        .iter()
        .map(|(stem, path)| {
            let text = fs::read_to_string(path).expect("read board yaml");
            let board = extract_top_level_string(&text, "name").unwrap_or_else(|| stem.clone());
            let chip = extract_top_level_string(&text, "chip").unwrap_or_default();
            BoardInfoLit { board, chip }
        })
        .collect();

    let mut out = fs::File::create(&out_path).expect("create generated.rs");
    writeln!(out, "// @generated by build.rs — do not edit.").unwrap();
    emit_match(&mut out, "chip_yaml_impl", &chips);
    emit_match(&mut out, "board_yaml_impl", &boards);
    emit_name_slice(&mut out, "CHIP_NAMES", &chips);
    emit_name_slice(&mut out, "BOARD_NAMES", &boards);
    emit_board_infos(&mut out, &board_infos);
}

struct BoardInfoLit {
    board: String,
    chip: String,
}

/// Extract the value of a top-level scalar key from a YAML document.
fn extract_top_level_string(text: &str, key: &str) -> Option<String> {
    for line in text.lines() {
        let bytes = line.as_bytes();
        if bytes.first().map(|b| b.is_ascii_whitespace() || *b == b'#') == Some(true) {
            continue;
        }
        let Some(rest) = line.strip_prefix(key) else {
            continue;
        };
        let Some(value) = rest.strip_prefix(':') else {
            continue;
        };
        let trimmed = value.trim();
        let trimmed = trimmed.split('#').next().unwrap_or("").trim();
        let unquoted = trimmed
            .strip_prefix('"')
            .and_then(|s| s.strip_suffix('"'))
            .or_else(|| {
                trimmed
                    .strip_prefix('\'')
                    .and_then(|s| s.strip_suffix('\''))
            })
            .unwrap_or(trimmed);
        if unquoted.is_empty() {
            return None;
        }
        return Some(unquoted.to_string());
    }
    None
}

fn collect_yaml(dir: &Path) -> Vec<(String, PathBuf)> {
    let mut out = Vec::new();
    let Ok(entries) = fs::read_dir(dir) else {
        return out;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("yaml") {
            continue;
        }
        println!("cargo:rerun-if-changed={}", path.display());
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("utf8 stem")
            .to_string();
        out.push((stem, path));
    }
    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}

fn overlay_into(dst: &mut Vec<(String, PathBuf)>, overlay_dir: &Path) {
    for (name, path) in collect_yaml(overlay_dir) {
        if let Some(existing) = dst.iter_mut().find(|(n, _)| *n == name) {
            existing.1 = path;
        } else {
            dst.push((name, path));
        }
    }
    dst.sort_by(|a, b| a.0.cmp(&b.0));
}

fn emit_match(out: &mut fs::File, fn_name: &str, entries: &[(String, PathBuf)]) {
    writeln!(
        out,
        "pub(crate) fn {fn_name}(name: &str) -> Option<&'static str> {{"
    )
    .unwrap();
    writeln!(out, "    match name {{").unwrap();
    for (name, path) in entries {
        writeln!(
            out,
            "        \"{name}\" => Some(include_str!(r\"{}\")),",
            path.display()
        )
        .unwrap();
    }
    writeln!(out, "        _ => None,").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
}

fn emit_name_slice(out: &mut fs::File, const_name: &str, entries: &[(String, PathBuf)]) {
    writeln!(out, "pub(crate) const {const_name}: &[&str] = &[").unwrap();
    for (name, _) in entries {
        writeln!(out, "    \"{name}\",").unwrap();
    }
    writeln!(out, "];").unwrap();
}

fn emit_board_infos(out: &mut fs::File, infos: &[BoardInfoLit]) {
    writeln!(
        out,
        "pub(crate) const BOARD_INFOS: &[crate::BoardInfo] = &["
    )
    .unwrap();
    for info in infos {
        writeln!(
            out,
            "    crate::BoardInfo {{ board: \"{}\", chip: \"{}\" }},",
            info.board.replace('"', "\\\""),
            info.chip.replace('"', "\\\"")
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
}
