[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
runner = "arm-none-eabi-gdb"

[env]
CARGO_INCREMENTAL = "0"
RUSTFLAGS = "-Zinstrument-coverage"
LLVM_PROFILE_FILE = "coverage-%p-%m.profraw"

[target.'cfg(all())']
rustflags = [
    "-C", "link-dead-code",
    "-C", "opt-level=0",
    "-C", "debuginfo=2",
]

