# Configuration for rlvgl-chips-microchip crate.
[package]
name = "rlvgl-chips-microchip"
version = "0.0.1"
edition = "2021"
publish = true
readme = "README.md"

[lib]
crate-type = ["rlib"]

[dependencies]
serde = { version = "1", features = ["derive"], optional = true }
