/* Generated by rlvgl-creator from chipdb/rlvgl-chips-esp/db/chips/esp32_c3.yaml.
 *
 * MEMORY block for ESP32-C3 (rv32imc). Each region
 * comes from the chip yaml's `memory:` array and is sized by the TRM
 * cited there. The REGION_ALIAS lines map the chip's regions onto the
 * generic names that riscv-rt's link.x consumes (REGION_TEXT, REGION_DATA,
 * etc.) — the alias targets come from the chip yaml's `linker:` section.
 */

MEMORY
{
  IROM_INTERNAL : ORIGIN = 0x40000000, LENGTH = 0x00040000    /* rx */
  IROM1_INTERNAL : ORIGIN = 0x40040000, LENGTH = 0x00020000    /* rx */
  DROM1_INTERNAL : ORIGIN = 0x3FF00000, LENGTH = 0x00020000    /* r */
  IRAM : ORIGIN = 0x4037C000, LENGTH = 0x00064000    /* rwx */
  DRAM : ORIGIN = 0x3FC80000, LENGTH = 0x00050000    /* rw */
  DROM : ORIGIN = 0x3C000000, LENGTH = 0x00800000    /* r */
  IROM : ORIGIN = 0x42000000, LENGTH = 0x00800000    /* rx */
  RTC_FAST_DATA : ORIGIN = 0x3FF80000, LENGTH = 0x00002000    /* rw */
  RTC_FAST_INST : ORIGIN = 0x400C0000, LENGTH = 0x00002000    /* rwx */
  RTC_SLOW : ORIGIN = 0x50000000, LENGTH = 0x00002000    /* rwx */
}

/* Aliases consumed by riscv-rt's link.x. */
REGION_ALIAS("REGION_TEXT",   IROM);
REGION_ALIAS("REGION_RODATA", IROM);
REGION_ALIAS("REGION_DATA",   IRAM);
REGION_ALIAS("REGION_BSS",    IRAM);
REGION_ALIAS("REGION_HEAP",   IRAM);
REGION_ALIAS("REGION_STACK",  IRAM);