//! Generated board modules.
#[cfg(feature = "i2c1")]
pub mod i2c1;
#[cfg(feature = "i2c2")]
pub mod i2c2;
#[cfg(feature = "i2c3")]
pub mod i2c3;
#[cfg(feature = "i2c4")]
pub mod i2c4;
#[cfg(feature = "spi1")]
pub mod spi1;
#[cfg(feature = "spi2")]
pub mod spi2;
#[cfg(feature = "spi3")]
pub mod spi3;
#[cfg(feature = "uart4")]
pub mod uart4;
#[cfg(feature = "usart2")]
pub mod usart2;
