//! Board support package for Adafruit Feather M4 Express.
//!
//! Auto-generated by `rlvgl-creator bsp from-yaml --vendor microchip`. Do
//! not edit by hand. Regenerate from
//! `chipdb/rlvgl-chips-microchip/db/chips/ATSAMD51J19A.yaml` and
//! `chipdb/rlvgl-chips-microchip/db/boards/adafruit_feather_m4_express.yaml`.
//!
//! - Chip:    ATSAMD51J19A (TQFP64, cortex-m4f)
//! - PAC:     `atsamd51j19a` v0.7
//! - Flash:   0.5 MB on-chip
//! - Source:  DS60001507 rev F

#![no_std]
#![deny(missing_docs)]

pub mod board;
pub mod clocks;
pub mod io_mux;
pub mod pac;
pub mod peripherals;

pub use pac::init;