/* Auto-generated by rlvgl-creator
* SPDX-FileCopyrightText: 2020 STMicroelectronics
* SPDX-FileCopyrightText: 2025 Softoboros Technology, Inc.
* SPDX-License-Identifier: BSD-3-Clause
* Provenance: STM32_open_pin_data (commit <hash>), build <build-hash>.

*/

//! HAL BSP for the generated board.

#![allow(non_snake_case)]
#![allow(clippy::too_many_arguments)]
#![cfg(feature = "usart1")]

use stm32h5xx_hal::{gpio::Speed, gpiob::*, pac, prelude::*};

/// Enables GPIO clocks required by the generated board.

pub fn enable_gpio_clocks(dp: &pac::Peripherals) {
    const MASK: u32 = (1u32 << 1);
    dp.RCC
        .ahb2enr
        .modify(|r, w| unsafe { w.bits(r.bits() | MASK) });
}

/// Configures pins using the HAL API.

pub fn configure_pins_hal(dp: &pac::Peripherals) {
    let gpiob = dp.GPIOB.split();

    // PB14 USART1_TX AF0
    let pb14 = gpiob.pb14.into_alternate::<0>();

    // PB15 USART1_RX AF0
    let pb15 = gpiob.pb15.into_alternate::<0>();
}

/// Enables peripheral clocks for the generated board.

pub fn enable_peripherals(dp: &pac::Peripherals) {}

/// De-initializes board peripherals and clocks.

pub fn deinit_board_hal(dp: &pac::Peripherals) {
    // Return pins to analog and remove pulls/open-drain
    let shift = 14 * 2;
    dp.GPIOB.moder.modify(|r, w| unsafe {
        let mut bits = r.bits() & !(0b11 << shift);
        bits |= 0b11 << shift;
        w.bits(bits)
    });
    dp.GPIOB
        .pupdr
        .modify(|r, w| unsafe { w.bits(r.bits() & !(0b11 << shift)) });
    dp.GPIOB
        .otyper
        .modify(|r, w| unsafe { w.bits(r.bits() & !(1 << 14)) });
    let shift = 15 * 2;
    dp.GPIOB.moder.modify(|r, w| unsafe {
        let mut bits = r.bits() & !(0b11 << shift);
        bits |= 0b11 << shift;
        w.bits(bits)
    });
    dp.GPIOB
        .pupdr
        .modify(|r, w| unsafe { w.bits(r.bits() & !(0b11 << shift)) });
    dp.GPIOB
        .otyper
        .modify(|r, w| unsafe { w.bits(r.bits() & !(1 << 15)) });

    // Gate peripheral clocks

    // Disable DMA controllers and mask their interrupts

    // Disable interrupts
    unsafe {
        pac::NVIC::mask(pac::Interrupt::USART1);
    }
}

/// Initializes the board using HAL drivers.

pub fn init_board_hal(dp: pac::Peripherals /*, clocks */) {
    enable_gpio_clocks(&dp);
    configure_pins_hal(&dp);
    enable_peripherals(&dp);
}
