#!/usr/bin/env bash
# CRATES-CI-01: Gate P staging — package every publishable crate in publish
# order, extract the packaged archives, and emit a cargo config-level
# [patch.crates-io] table that Consumer Projects drop into their
# .cargo/config.toml.
#
# Governed by docs/crates-ci/CRATES-CI-00-CONCEPTS.md (§5 gate topology,
# §6 Staged Registry mechanism, §9 invariant set):
#
#   - INV-C6: packages are built from a clean tree (refused otherwise, unless
#     ALLOW_DIRTY=1 for local iteration). Asset prep (stm32_afdb_pipeline /
#     gen_ioc_bsps) may dirty the tree AFTER the check; that is expected and
#     mirrors scripts/publish_changed.sh's publish-time behaviour.
#   - INV-C2: Consumer Projects carry zero path/[patch] routes into the
#     workspace. The paths emitted here point at EXTRACTED PACKAGE
#     directories under $STAGE_DIR/staged/ — the packaged file set, not the
#     workspace — so consuming them exercises P-INCLUDE/P-META/P-RESOLVE
#     exactly as §6 requires.
#
# Why [patch.crates-io] over a pure directory-source replacement of
# crates.io: a replaced crates.io source can only resolve versions that
# already exist in the upstream index — unpublished (about-to-be-released)
# versions are unresolvable from a directory source standing in for
# crates.io. [patch.crates-io] entries instead INJECT candidate versions
# that do not exist upstream, which is precisely what Gate P needs when
# staging a not-yet-published release set. This is the §6 mechanism as
# validated in CRATES-CI-01 (§6.4 reserves mechanism details for exactly
# this kind of validated adjustment).
#
# Env knobs:
#   STAGE_DIR        staging root (default: $REPO_ROOT/target/crates-ci)
#   ALLOW_DIRTY      1 = skip the INV-C6 clean-tree check and pass
#                    --allow-dirty to every cargo package (default: 0)
#   SKIP_ASSET_PREP  1 = skip stm32_afdb_pipeline.sh / gen_ioc_bsps.sh prep
#                    for fast local iteration (default: 0)
#   ONLY_CRATES      optional space-separated crate subset for local
#                    iteration; CI leaves this unset (full publish order)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

STAGE_DIR="${STAGE_DIR:-$REPO_ROOT/target/crates-ci}"
ALLOW_DIRTY="${ALLOW_DIRTY:-0}"
SKIP_ASSET_PREP="${SKIP_ASSET_PREP:-0}"
ONLY_CRATES="${ONLY_CRATES:-}"

# --- INV-C6: refuse a dirty tree BEFORE any prep -----------------------------
if [[ "$ALLOW_DIRTY" != "1" ]]; then
  if [[ -n "$(git status --porcelain)" ]]; then
    echo "Gate P: working tree is dirty; refusing to stage (INV-C6)." >&2
    echo "Gate P: commit/stash your changes, or set ALLOW_DIRTY=1 for local iteration." >&2
    exit 1
  fi
fi

# --- Ordered crate list (single source: publish_changed.sh) ------------------
ORDERED_CRATES="$(scripts/publish_changed.sh --print-order)"
if [[ -z "$ORDERED_CRATES" ]]; then
  echo "Gate P: scripts/publish_changed.sh --print-order returned no crates." >&2
  exit 1
fi

# --- Stage dir hygiene: deterministic reruns ---------------------------------
mkdir -p "$STAGE_DIR"
rm -rf "$STAGE_DIR/staged"
rm -f "$STAGE_DIR/patch-config.toml"
mkdir -p "$STAGE_DIR/staged"

# --- Crate versions from cargo metadata --------------------------------------
METADATA_JSON="$(mktemp)"
cleanup() {
  rm -f "$METADATA_JSON"
}
trap cleanup EXIT

cargo metadata --no-deps --format-version 1 >"$METADATA_JSON"
python3 - "$METADATA_JSON" >"$STAGE_DIR/versions.tsv" <<'PY'
import json
import sys

with open(sys.argv[1], "r", encoding="utf-8") as handle:
    metadata = json.load(handle)

for package in metadata["packages"]:
    print(f"{package['name']}\t{package['version']}")
PY

crate_version() {
  awk -F '\t' -v crate="$1" '$1 == crate { print $2; exit }' \
    "$STAGE_DIR/versions.tsv"
}

crate_selected() {
  local crate="$1"
  local only
  if [[ -z "$ONLY_CRATES" ]]; then
    return 0
  fi
  for only in $ONLY_CRATES; do
    if [[ "$only" == "$crate" ]]; then
      return 0
    fi
  done
  return 1
}

# --- Package + extract + patch, progressively, in publish order ----------------
#
# cargo package re-resolves the sanitized (path-deps-stripped) manifest, so a
# crate depending on a not-yet-published sibling version can only package if
# that sibling is already injectable. Publish time solves this by actually
# publishing in order; Gate P solves it by EXTRACTING each staged package and
# appending it to patch-config.toml BEFORE packaging the next crate, then
# feeding the partial patch table to cargo via --config. Bonus: a publish-order
# topology error now fails Gate P at the exact crate that would have failed
# `cargo publish` (failure class P-ORDER caught pre-tag).
PREP_DIRTIED=0
DRIFTED_CRATES=""
PATCH_CONFIG="$STAGE_DIR/patch-config.toml"
{
  echo "# Generated by scripts/crates_ci_stage.sh (CRATES-CI-01, Gate P)."
  echo "# Drop into a Consumer Project's .cargo/config.toml to consume the"
  echo "# staged (extracted-package) crate set instead of crates.io."
  echo "[patch.crates-io]"
} >"$PATCH_CONFIG"

package_crate() {
  # $1 = crate, remaining args = extra cargo package flags
  local crate="$1"
  shift
  local log
  log="$(mktemp)"
  if ! cargo --config "$PATCH_CONFIG" package --no-verify -p "$crate" "$@" 2>&1 \
      | tee "$log"; then
    rm -f "$log"
    echo "Gate P: cargo package failed for $crate" >&2
    exit 1
  fi
  # P-META hard gate: cargo package only WARNS about missing description /
  # license, but cargo publish hard-fails on them — exactly how the
  # disco-assets "no manifest metadata" publish failure slipped past Gate P.
  # Promote the publish-fatal subset of warnings to errors here.
  if grep -qE 'manifest has no (description|license)' "$log"; then
    grep -E 'manifest has no' "$log" >&2
    rm -f "$log"
    echo "Gate P: $crate manifest is missing publish-required metadata (P-META)" >&2
    exit 1
  fi
  rm -f "$log"
}

# Version-drift gate: a crate whose version already exists on crates.io MUST
# have identical content — otherwise the publish script's "already published"
# skip silently ships stale code (the disco-assets / rlvgl-widgets class).
# Compares the packaged archive against the published one, ignoring members
# that legitimately differ run-to-run (.cargo_vcs_info.json embeds the git
# sha; Cargo.toml is normalizer-version-dependent; Cargo.lock is resolver
# churn). Exit: 0 = not published or identical, 4 = real content drift.
check_published_drift() {
  # $1 = crate, $2 = version, $3 = packaged .crate path
  python3 - "$1" "$2" "$3" <<'PY'
import hashlib, io, json, sys, tarfile, urllib.error, urllib.request

crate, version, archive = sys.argv[1], sys.argv[2], sys.argv[3]
n = crate.lower()
if len(n) >= 4:
    path = f"{n[:2]}/{n[2:4]}/{n}"
elif len(n) == 3:
    path = f"3/{n}"
else:
    path = f"{len(n)}/{n}"

def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "rlvgl-crates-ci"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()

try:
    body = fetch(f"https://index.crates.io/{path}").decode()
except urllib.error.HTTPError as e:
    if e.code == 404:
        sys.exit(0)  # crate never published
    print(f"Gate P: index query failed for {crate}: {e}", file=sys.stderr)
    sys.exit(3)
except Exception as e:
    print(f"Gate P: index query failed for {crate}: {e}", file=sys.stderr)
    sys.exit(3)

entry = next((json.loads(l) for l in body.splitlines()
              if json.loads(l).get("vers") == version), None)
if entry is None:
    sys.exit(0)  # this exact version not published — fresh publish, no drift

local_bytes = open(archive, "rb").read()
if hashlib.sha256(local_bytes).hexdigest() == entry.get("cksum"):
    sys.exit(0)  # byte-identical to the published archive

# Checksums differ — compare member contents, ignoring run-variant members.
IGNORE = {"Cargo.toml", "Cargo.lock", ".cargo_vcs_info.json"}
def members(data):
    out = {}
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as tf:
        for m in tf.getmembers():
            if not m.isfile():
                continue
            rel = m.name.split("/", 1)[1] if "/" in m.name else m.name
            if rel in IGNORE:
                continue
            out[rel] = hashlib.sha256(tf.extractfile(m).read()).hexdigest()
    return out

try:
    published = members(fetch(
        f"https://static.crates.io/crates/{crate}/{crate}-{version}.crate"))
except Exception as e:
    print(f"Gate P: could not download published {crate} v{version}: {e}",
          file=sys.stderr)
    sys.exit(3)
local = members(local_bytes)
if local != published:
    diff = sorted(set(local) ^ set(published)) or sorted(
        k for k in local if local[k] != published.get(k))
    print(f"Gate P: {crate} v{version} is already on crates.io with "
          f"DIFFERENT content (changed: {', '.join(diff[:8])}) — bump the "
          f"version or the publish skip will ship stale code.",
          file=sys.stderr)
    sys.exit(4)
sys.exit(0)  # content-identical; cksum delta is packaging-tool variance
PY
}

stage_crate() {
  # Extract the freshly packaged archive and append its patch entry so every
  # SUBSEQUENT cargo package resolves this crate from the staged package.
  local crate="$1"
  local version
  version="$(crate_version "$crate")"
  if [[ -z "$version" ]]; then
    echo "Gate P: could not determine workspace version for $crate." >&2
    exit 1
  fi

  local archive="$REPO_ROOT/target/package/${crate}-${version}.crate"
  if [[ ! -f "$archive" ]]; then
    echo "Gate P: packaged archive missing for $crate: $archive" >&2
    exit 1
  fi

  tar xzf "$archive" -C "$STAGE_DIR/staged"
  if [[ ! -d "$STAGE_DIR/staged/${crate}-${version}" ]]; then
    echo "Gate P: extraction did not produce $STAGE_DIR/staged/${crate}-${version}" >&2
    exit 1
  fi

  echo "${crate} = { path = \"$STAGE_DIR/staged/${crate}-${version}\" }" \
    >>"$PATCH_CONFIG"
}

staged_count=0
while IFS= read -r crate; do
  [[ -n "$crate" ]] || continue
  if ! crate_selected "$crate"; then
    continue
  fi

  if [[ "$crate" == "rlvgl-chips-stm" && "$SKIP_ASSET_PREP" != "1" ]]; then
    # Mirrors publish-time prep in scripts/publish_changed.sh: the packaged
    # chip database archive is generated at publish time and gitignored
    # in-tree, so force-add it for cargo packaging.
    scripts/stm32_afdb_pipeline.sh
    git add -f chipdb/rlvgl-chips-stm/assets/chipdb.bin.zst
    PREP_DIRTIED=1
    package_crate "$crate" --allow-dirty
  elif [[ "$crate" == "rlvgl-bsps-stm" && "$SKIP_ASSET_PREP" != "1" ]]; then
    # Mirrors publish-time prep in scripts/publish_changed.sh.
    scripts/gen_ioc_bsps.sh
    PREP_DIRTIED=1
    package_crate "$crate" --allow-dirty
  elif [[ "$ALLOW_DIRTY" == "1" || "$PREP_DIRTIED" == "1" ]]; then
    package_crate "$crate" --allow-dirty
  else
    package_crate "$crate"
  fi

  stage_crate "$crate"

  # Version-drift gate (skippable for airgapped local runs via
  # CRATES_CI_OFFLINE=1; CI always runs it). The two asset-bearing crates
  # are ALWAYS exempt: their packaged content embeds pipeline-regenerated
  # artifacts (chipdb.bin.zst from stm32_afdb_pipeline.sh, the gen_ioc_bsps
  # output) that are legitimately non-byte-reproducible run-to-run, so a
  # content compare against the published archive always flags (verified:
  # only assets/chipdb.bin.zst differs on an otherwise untouched crate).
  # Their source-change → publish discipline is carried by the path
  # mappings in publish_changed.sh instead.
  if [[ "$crate" == "rlvgl-chips-stm" || "$crate" == "rlvgl-bsps-stm" ]]; then
    echo "Gate P: drift check exempt for $crate (pipeline-regenerated assets are not byte-reproducible)"
  elif [[ "${CRATES_CI_OFFLINE:-0}" != "1" ]]; then
    version="$(crate_version "$crate")"
    if ! check_published_drift "$crate" "$version" \
        "$REPO_ROOT/target/package/${crate}-${version}.crate"; then
      DRIFTED_CRATES="${DRIFTED_CRATES}${crate} v${version}
"
    fi
  fi

  staged_count=$((staged_count + 1))
done <<EOF
$ORDERED_CRATES
EOF

if [[ "$staged_count" -eq 0 ]]; then
  echo "Gate P: no crates matched ONLY_CRATES='$ONLY_CRATES'; nothing staged." >&2
  exit 1
fi

if [[ -n "$DRIFTED_CRATES" ]]; then
  echo "Gate P: version drift — these crates are already published at the" >&2
  echo "same version with DIFFERENT content; bump their versions:" >&2
  printf '%s' "$DRIFTED_CRATES" | sed 's/^/  - /' >&2
  exit 1
fi

# --- Summary -------------------------------------------------------------------
echo "Gate P staging complete:"
echo "  crates staged : $staged_count"
echo "  stage dir     : $STAGE_DIR"
echo "  versions      : $STAGE_DIR/versions.tsv"
echo "  patch config  : $PATCH_CONFIG"
echo "Consumers consume the staged set via patch-config.toml — drop its"
echo "[patch.crates-io] table into the Consumer Project's .cargo/config.toml."
