[package]
name = "rlvgl-sim"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
rlvgl= { version = "0.1.4", path = "../..", features = ["simulator"], default-features = false }

[[bin]]
name = "rlvgl-sim"
path = "main.rs"
