[package]
name = "rlvgl-example-sim"
version = "0.2.0"
edition = "2024"
publish = false

[[bin]]
name = "rlvgl-sim"
path = "src/main.rs"

[features]
default = ["png", "jpeg", "gif", "qrcode", "fontdue"]
png = ["rlvgl-app-demo/png", "rlvgl-core/png"]
jpeg = ["rlvgl-app-demo/jpeg", "rlvgl-core/jpeg"]
gif = ["rlvgl-app-demo/gif", "rlvgl-core/gif"]
qrcode = ["rlvgl-app-demo/qrcode", "rlvgl-core/qrcode"]
fontdue = ["rlvgl-app-demo/fontdue", "rlvgl-core/fontdue"]
cpu_stats = []

[dependencies]
rlvgl-core = { path = "../../core", default-features = false }
rlvgl-platform = { path = "../../platform", features = ["simulator"] }
rlvgl-app-demo = { path = "../apps/demo", default-features = false }

[dev-dependencies]
tempfile = "3"
