[package]
name = "rlvgl-sim"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
rlvgl= { path = "../..", features = ["simulator", "qrcode", "png", "fontdue"], default-features = false }

[features]
default = ["fontdue"]
fontdue = []
