[package]
name = "rlvgl-stm-bsps"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Board support package stubs for STM32 devices."

[lib]
path = "src/lib.rs"

[features]
default = [
    "hal",
    "split",
]
hal = []
pac = []
split = []
flat = []
summaries = []
pinreport = []
stm32-f4 = []
