# Configuration for rlvgl-chips-ti crate.
[package]
name = "rlvgl-chips-ti"
version = "0.2.0"
authors = ["Ira Abbott <ira@softoboros.com>"]
edition = "2021"
license = "MIT"
description = "Texas Instruments chip database adapter for rlvgl code generation."
publish = true
readme = "README.md"
repository = "https://github.com/softoboros/rlvgl"
homepage = "https://github.com/softoboros/rlvgl"
documentation = "https://docs.rs/rlvgl-chips-ti"
keywords = ["embedded", "ti", "mcu", "chipdb", "no_std"]
categories = ["config", "embedded"]

[lib]
crate-type = ["rlib"]

[dependencies]
serde = { version = "1", features = ["derive"], optional = true }
