/* Auto-generated by rlvgl-creator
* SPDX-FileCopyrightText: 2020 STMicroelectronics
* SPDX-FileCopyrightText: 2025 Softoboros Technology, Inc.
* SPDX-License-Identifier: BSD-3-Clause
* Provenance: STM32_open_pin_data (commit <hash>), build <build-hash>.

*/

//! PAC BSP for the generated board.

#![allow(non_snake_case)]
#![allow(clippy::too_many_arguments)]
#![cfg(feature = "spi5")]

use stm32h7::stm32h743 as pac;

/// Enables GPIO clocks required by the generated board.

pub fn enable_gpio_clocks(dp: &pac::Peripherals) {
    const MASK: u32 = (1u32 << 9) | (1u32 << 10);
    dp.RCC
        .ahb4enr
        .modify(|r, w| unsafe { w.bits(r.bits() | MASK) });
}

/// Configures pins using PAC registers.

pub fn configure_pins_pac(dp: &pac::Peripherals) {
    // GPIOJ
    dp.GPIOJ.pupdr.modify(|r, w| unsafe {
        let mut bits = r.bits();
        let shift = 10 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b00 << shift;
        let shift = 11 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b00 << shift;
        w.bits(bits)
    });
    dp.GPIOJ.otyper.modify(|r, w| unsafe {
        let mut bits = r.bits();
        bits &= !(1 << 10);
        bits &= !(1 << 11);
        w.bits(bits)
    });
    dp.GPIOJ.ospeedr.modify(|r, w| unsafe {
        let mut bits = r.bits();
        let shift = 10 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b11 << shift;
        let shift = 11 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b11 << shift;
        w.bits(bits)
    });
    dp.GPIOJ.afrl.modify(|r, w| unsafe {
        let mut bits = r.bits();
        w.bits(bits)
    });
    dp.GPIOJ.afrh.modify(|r, w| unsafe {
        let mut bits = r.bits();
        let afr_shift = (10 % 8) * 4;
        bits &= !(0xF << afr_shift);
        bits |= (0u32 & 0xF) << afr_shift;
        let afr_shift = (11 % 8) * 4;
        bits &= !(0xF << afr_shift);
        bits |= (0u32 & 0xF) << afr_shift;
        w.bits(bits)
    });
    dp.GPIOJ.moder.modify(|r, w| unsafe {
        let mut bits = r.bits();
        let shift = 10 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b10 << shift;
        let shift = 11 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b10 << shift;
        w.bits(bits)
    });

    // GPIOK
    dp.GPIOK.pupdr.modify(|r, w| unsafe {
        let mut bits = r.bits();
        let shift = 0 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b00 << shift;
        let shift = 1 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b00 << shift;
        w.bits(bits)
    });
    dp.GPIOK.otyper.modify(|r, w| unsafe {
        let mut bits = r.bits();
        bits &= !(1 << 0);
        bits &= !(1 << 1);
        w.bits(bits)
    });
    dp.GPIOK.ospeedr.modify(|r, w| unsafe {
        let mut bits = r.bits();
        let shift = 0 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b11 << shift;
        let shift = 1 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b11 << shift;
        w.bits(bits)
    });
    dp.GPIOK.afrl.modify(|r, w| unsafe {
        let mut bits = r.bits();
        w.bits(bits)
    });
    dp.GPIOK.afrh.modify(|r, w| unsafe {
        let mut bits = r.bits();
        let afr_shift = (0 % 8) * 4;
        bits &= !(0xF << afr_shift);
        bits |= (0u32 & 0xF) << afr_shift;
        let afr_shift = (1 % 8) * 4;
        bits &= !(0xF << afr_shift);
        bits |= (0u32 & 0xF) << afr_shift;
        w.bits(bits)
    });
    dp.GPIOK.moder.modify(|r, w| unsafe {
        let mut bits = r.bits();
        let shift = 0 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b10 << shift;
        let shift = 1 * 2;
        bits &= !(0b11 << shift);
        bits |= 0b10 << shift;
        w.bits(bits)
    });
}

/// Disables unused peripherals and masks their interrupts.

/// Enables peripheral clocks for the generated board using PAC registers.

pub fn enable_peripherals(_dp: &pac::Peripherals) {}

/// De-initializes board pins to their analog state.

/// De-initializes board peripherals and clocks using PAC registers.

pub fn deinit_board_pac(dp: &pac::Peripherals) {
    // Return pins to analog and remove pulls/open-drain
    let shift = 10 * 2;
    dp.GPIOJ.moder.modify(|r, w| unsafe {
        let mut bits = r.bits() & !(0b11 << shift);
        bits |= 0b11 << shift;
        w.bits(bits)
    });
    dp.GPIOJ
        .pupdr
        .modify(|r, w| unsafe { w.bits(r.bits() & !(0b11 << shift)) });
    dp.GPIOJ
        .otyper
        .modify(|r, w| unsafe { w.bits(r.bits() & !(1 << 10)) });
    let shift = 11 * 2;
    dp.GPIOJ.moder.modify(|r, w| unsafe {
        let mut bits = r.bits() & !(0b11 << shift);
        bits |= 0b11 << shift;
        w.bits(bits)
    });
    dp.GPIOJ
        .pupdr
        .modify(|r, w| unsafe { w.bits(r.bits() & !(0b11 << shift)) });
    dp.GPIOJ
        .otyper
        .modify(|r, w| unsafe { w.bits(r.bits() & !(1 << 11)) });
    let shift = 0 * 2;
    dp.GPIOK.moder.modify(|r, w| unsafe {
        let mut bits = r.bits() & !(0b11 << shift);
        bits |= 0b11 << shift;
        w.bits(bits)
    });
    dp.GPIOK
        .pupdr
        .modify(|r, w| unsafe { w.bits(r.bits() & !(0b11 << shift)) });
    dp.GPIOK
        .otyper
        .modify(|r, w| unsafe { w.bits(r.bits() & !(1 << 0)) });
    let shift = 1 * 2;
    dp.GPIOK.moder.modify(|r, w| unsafe {
        let mut bits = r.bits() & !(0b11 << shift);
        bits |= 0b11 << shift;
        w.bits(bits)
    });
    dp.GPIOK
        .pupdr
        .modify(|r, w| unsafe { w.bits(r.bits() & !(0b11 << shift)) });
    dp.GPIOK
        .otyper
        .modify(|r, w| unsafe { w.bits(r.bits() & !(1 << 1)) });

    // Gate peripheral clocks

    // Disable DMA controllers and mask their interrupts

    // Disable interrupts
    unsafe {
        pac::NVIC::mask(pac::Interrupt::SPI5);
    }
}
