/* Auto-generated by rlvgl-creator
* SPDX-FileCopyrightText: 2020 STMicroelectronics
* SPDX-FileCopyrightText: 2025 Softoboros Technology, Inc.
* SPDX-License-Identifier: BSD-3-Clause
* Provenance: STM32_open_pin_data (commit <hash>), build <build-hash>.

*/

//! HAL BSP for the generated board.

#![allow(non_snake_case)]
#![allow(clippy::too_many_arguments)]
#![cfg(feature = "spi1")]

use stm32mp1_hal::{gpio::Speed, gpiod::*, gpioi::*, pac, prelude::*};

/// Enables GPIO clocks required by the generated board.

pub fn enable_gpio_clocks(dp: &pac::Peripherals) {
    const MASK: u32 = (1u32 << 3) | (1u32 << 8);
    dp.RCC
        .ahb1enr
        .modify(|r, w| unsafe { w.bits(r.bits() | MASK) });
}

/// Configures pins using the HAL API.

pub fn configure_pins_hal(dp: &pac::Peripherals) {
    let gpiod = dp.GPIOD.split();

    let gpioi = dp.GPIOI.split();

    // PD1 SPI1_MISO AF0
    let pd1 = gpiod.pd1.into_alternate::<0>().set_speed(Speed::VeryHigh);

    // PD11 SPI1_SCK AF0
    let pd11 = gpiod.pd11.into_alternate::<0>().set_speed(Speed::VeryHigh);

    // PD2 SPI1_NSS AF0
    let pd2 = gpiod.pd2.into_alternate::<0>().set_speed(Speed::VeryHigh);

    // PI5 SPI1_MOSI AF0
    let pi5 = gpioi.pi5.into_alternate::<0>().set_speed(Speed::VeryHigh);
}

/// Enables peripheral clocks for the generated board.

pub fn enable_peripherals(dp: &pac::Peripherals) {}

/// De-initializes board peripherals and clocks.

pub fn deinit_board_hal(dp: &pac::Peripherals) {
    // Return pins to analog and remove pulls/open-drain
    let shift = 1 * 2;
    dp.GPIOD.moder.modify(|r, w| unsafe {
        let mut bits = r.bits() & !(0b11 << shift);
        bits |= 0b11 << shift;
        w.bits(bits)
    });
    dp.GPIOD
        .pupdr
        .modify(|r, w| unsafe { w.bits(r.bits() & !(0b11 << shift)) });
    dp.GPIOD
        .otyper
        .modify(|r, w| unsafe { w.bits(r.bits() & !(1 << 1)) });
    let shift = 11 * 2;
    dp.GPIOD.moder.modify(|r, w| unsafe {
        let mut bits = r.bits() & !(0b11 << shift);
        bits |= 0b11 << shift;
        w.bits(bits)
    });
    dp.GPIOD
        .pupdr
        .modify(|r, w| unsafe { w.bits(r.bits() & !(0b11 << shift)) });
    dp.GPIOD
        .otyper
        .modify(|r, w| unsafe { w.bits(r.bits() & !(1 << 11)) });
    let shift = 2 * 2;
    dp.GPIOD.moder.modify(|r, w| unsafe {
        let mut bits = r.bits() & !(0b11 << shift);
        bits |= 0b11 << shift;
        w.bits(bits)
    });
    dp.GPIOD
        .pupdr
        .modify(|r, w| unsafe { w.bits(r.bits() & !(0b11 << shift)) });
    dp.GPIOD
        .otyper
        .modify(|r, w| unsafe { w.bits(r.bits() & !(1 << 2)) });
    let shift = 5 * 2;
    dp.GPIOI.moder.modify(|r, w| unsafe {
        let mut bits = r.bits() & !(0b11 << shift);
        bits |= 0b11 << shift;
        w.bits(bits)
    });
    dp.GPIOI
        .pupdr
        .modify(|r, w| unsafe { w.bits(r.bits() & !(0b11 << shift)) });
    dp.GPIOI
        .otyper
        .modify(|r, w| unsafe { w.bits(r.bits() & !(1 << 5)) });

    // Gate peripheral clocks

    // Disable DMA controllers and mask their interrupts

    // Disable interrupts
}

/// Initializes the board using HAL drivers.

pub fn init_board_hal(dp: pac::Peripherals /*, clocks */) {
    enable_gpio_clocks(&dp);
    configure_pins_hal(&dp);
    enable_peripherals(&dp);
}
