// SPDX-License-Identifier: MIT
//
// Generated by `rlvgl-creator qt emit --target rlvgl` from `/Users/iraabbott/softoboros/ops/packer/submodules/scjson/tutorial/Examples/Qt/SkodaBoleroInfotainment/Qml/Media/FrameMedia.qml`.
// Do not edit by hand — regenerate with:
//   cargo run --features creator --bin rlvgl-creator -- \
//       qt emit --target rlvgl <input.qml> <out_dir>
//
// Emit-shape contract: docs/qt-support/03b-rlvgl-widget-mapping.md
// QT-03b notes:
//   * helper functions named per §8 (`build_<sanitized_id>` /
//     `build_node_<index>`) so reviewers have stable handles.
//   * bounds resolved per §7 trivial path; non-`fill`/`margins`
//     anchors are deferred to QT-03c.
//   * property lowering per §6; unsupported lower to TODOs.
// QT-04b notes (docs/qt-support/04b-properties-bindings.md):
//   * `pub struct ScreenState` carries every QML root-level
//     property declaration (see §3 / §5).
//   * `build_screen` returns `(WidgetNode, Rc<RefCell<ScreenState>>)`
//     and threads `state` through every helper.
//   * Handler bodies that match the §7 grammar lower to
//     `state.borrow_mut()...` mutations under a `// QT-04b body:`
//     marker; non-matching bodies fall through to `// QT-04 body:`.

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_variables)]

extern crate alloc;

use crate::qt_assets;
use alloc::rc::Rc;
use alloc::string::String;
use alloc::vec::Vec;
use core::cell::RefCell;

use rlvgl_core::WidgetNode;
use rlvgl_core::widget::{Color, Rect, Widget};
use rlvgl_widgets::button::Button;
use rlvgl_widgets::click_area::ClickArea;
use rlvgl_widgets::container::Container;
use rlvgl_widgets::image::Image;
use rlvgl_widgets::label::Label;

/// rlvgl-target emit-shape version. Bumping is Specification-Required
/// (see `docs/qt-support/04b-properties-bindings.md` §11).
pub const QT_EMIT_VERSION: u32 = 14;

/// `qt-ir` schema version this module was generated from.
pub const QT_IR_VERSION: u32 = 2;

/// Source `.qml` file path as recorded at emit time.
pub const QT_SOURCE: &str = "/Users/iraabbott/softoboros/ops/packer/submodules/scjson/tutorial/Examples/Qt/SkodaBoleroInfotainment/Qml/Media/FrameMedia.qml";

/// State threaded through every helper. One field per
/// QT-04b §5-supported property declared on the QML root.
/// `#[rustfmt::skip]` so the field order matches QT-01a's IR
/// declaration order rather than rustfmt's alphabetical sort.
#[rustfmt::skip]
#[derive(Debug, Clone)]
pub struct ScreenState {
    pub i_ROW_SPACING: i32,
    pub panelHeight: i32,
    pub repeatBtn_itemSelected: bool,
    pub repeatBtn_topBorderVisible: bool,
    pub repeatBtn_highlightBackgroundWhenSelected: bool,
    pub repeatBtn_gradientColor: String,
    pub shapePath_iOffset: i32,
    pub warningPanel_code: i32,
}

/// Reactive Label-text binding emitted by QT-04e §3. Each
/// entry pairs a concrete `Rc<RefCell<Label>>` with an
/// accessor that reads the bound state field. Use
/// [`refresh_bindings`] to re-apply every binding in one call.
pub struct LabelBinding {
    pub label: Rc<RefCell<Label>>,
    pub accessor: fn(&ScreenState) -> String,
}

impl LabelBinding {
    /// Re-apply this binding from the supplied state.
    pub fn refresh(&self, state: &ScreenState) {
        self.label.borrow_mut().set_text((self.accessor)(state));
    }
}

/// Build the screen widget tree at `bounds` and return it
/// alongside the `ScreenState` handle (QT-04b) and the
/// `Vec<LabelBinding>` of reactive bindings (QT-04e §3).
/// Callers ignore the third element with a `_` if reactivity
/// is not needed.
#[rustfmt::skip]
pub fn build_screen(
    bounds: Rect,
) -> (WidgetNode, Rc<RefCell<ScreenState>>, Vec<LabelBinding>) {
    let state = Rc::new(RefCell::new(ScreenState {
        i_ROW_SPACING: 3,
        // QT-04b: non-literal default for `panelHeight`: height / 6 - AppConsts.i_DISPLAY_PADDING
        panelHeight: 0,
        repeatBtn_itemSelected: false,
        repeatBtn_topBorderVisible: true,
        repeatBtn_highlightBackgroundWhenSelected: false,
        // QT-04b: non-literal default for `gradientColor`: AppConsts.cl_ITEM_COLOR
        repeatBtn_gradientColor: String::new(),
        shapePath_iOffset: 7,
        // QT-04b: non-literal default for `code`: getCode()
        warningPanel_code: 0,
    }));
    let mut label_bindings: Vec<LabelBinding> = Vec::new();
    let node = build_pane(bounds, Rc::clone(&state), &mut label_bindings);
    (node, state, label_bindings)
}

/// Re-apply every QT-04e binding from the current state.
/// Idempotent; safe to call after every `state.borrow_mut()`
/// mutation. No-op when `bindings` is empty.
pub fn refresh_bindings(state: &Rc<RefCell<ScreenState>>, bindings: &[LabelBinding]) {
    let s = state.borrow();
    for b in bindings {
        b.refresh(&s);
    }
}

// Required `qt_assets` symbols (one RLE `&[u8]` blob each):
//   qt_assets::IMG_IMGBOLEROBACKGROUND  ←  Images/ImgBoleroBackground.png
//   qt_assets::IMG_IMGMUTE  ←  Images/ImgMute.png
//   qt_assets::IMG_IMGMEDIATRACKREPEAT_48  ←  Qml/Images/ImgMediaTrackRepeat_48.png
//   qt_assets::IMG_IMGSHUFFLEON_48  ←  Qml/Images/ImgShuffleOn_48.png
/// Decode a vendored RLE asset into an owned, leaked pixel buffer and
/// wrap it in an `Image` widget (see emit-time docs above).
#[rustfmt::skip]
fn qt_image(bounds: Rect, rle: &'static [u8]) -> Rc<RefCell<dyn Widget>> {
    let (w, h, palette_bytes, stream) =
        rlvgl_decomp::parse_rle_blob(rle).expect("qt_image: malformed RLE asset");
    let palette_len = palette_bytes.len() / 2;
    let mut palette = alloc::vec![0u16; palette_len];
    for i in 0..palette_len {
        palette[i] = u16::from_le_bytes([palette_bytes[i * 2], palette_bytes[i * 2 + 1]]);
    }
    let rgba = rlvgl_decomp::decode_rgba(w as usize, h as usize, &palette, stream)
        .expect("qt_image: RLE decode failed");
    let pixels: Vec<Color> = rgba
        .chunks_exact(4)
        .map(|c| Color(c[0], c[1], c[2], c[3]))
        .collect();
    let pixels: &'static [Color] = Vec::leak(pixels);
    Rc::new(RefCell::new(Image::new(bounds, w as i32, h as i32, pixels)))
}

// QML type: `Image` (id: `pane`)
#[rustfmt::skip]
fn build_pane(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // QT-IMG: Image source → qt_assets::IMG_IMGBOLEROBACKGROUND (Images/ImgBoleroBackground.png)
    let widget: Rc<RefCell<dyn Widget>> = qt_image(bounds, qt_assets::IMG_IMGBOLEROBACKGROUND);
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("pane"),
    };
    let child_bounds = bounds;
    node.children.push(build_paneMouseArea(child_bounds, Rc::clone(&state), label_bindings));
    node
}

// QML type: `MouseArea` (id: `paneMouseArea`)
#[rustfmt::skip]
fn build_paneMouseArea(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    let mut click_area = ClickArea::new(bounds);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(click_area));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("paneMouseArea"),
    };
    let cb_2 = Rect {
        x: bounds.x,
        y: (((bounds.y + bounds.height)) - (bounds.height)),
        width: (((bounds.x + bounds.width)) - (bounds.x)),
        height: bounds.height,
    };
    let cb_0 = Rect {
        x: bounds.x,
        y: bounds.y,
        width: (((bounds.x + bounds.width)) - (bounds.x)),
        height: ((cb_2.y) - (bounds.y)),
    };
    let cb_1 = Rect {
        x: bounds.x,
        y: bounds.y,
        width: (((bounds.x + bounds.width)) - (bounds.x)),
        height: (((bounds.y + bounds.height)) - (bounds.y)),
    };
    node.children.push(build_contentPaddingItem(cb_0, Rc::clone(&state), label_bindings));
    node.children.push(build_node_3(cb_1, Rc::clone(&state), label_bindings));
    node.children.push(build_bottomPanel(cb_2, Rc::clone(&state), label_bindings));
    node
}

// QML type: `Item` (id: `contentPaddingItem`)
#[rustfmt::skip]
fn build_contentPaddingItem(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Container::new(bounds)));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("contentPaddingItem"),
    };
    let cb_0 = Rect {
        x: bounds.x,
        y: bounds.y,
        width: (((bounds.x + bounds.width)) - (bounds.x)),
        height: bounds.height,
    };
    let cb_1 = Rect {
        x: bounds.x,
        y: ((((bounds.y + bounds.height) - 10)) - (bounds.height)),
        width: (((bounds.x + bounds.width)) - (bounds.x)),
        height: bounds.height,
    };
    let cb_3 = Rect {
        x: (((bounds.x + bounds.width)) - (160)),
        y: (cb_0.y + cb_0.height),
        width: 160,
        height: 160,
    };
    let cb_2 = Rect {
        x: bounds.x,
        y: (cb_3.y + cb_3.height),
        width: (((bounds.x + bounds.width)) - (bounds.x)),
        height: ((cb_1.y) - ((cb_3.y + cb_3.height))),
    };
    let cb_4 = Rect {
        x: (bounds.x + 10),
        y: cb_3.y,
        width: (((cb_3.x - 10)) - ((bounds.x + 10))),
        height: (((cb_3.y + cb_3.height)) - (cb_3.y)),
    };
    let cb_5 = Rect {
        x: bounds.x,
        y: (cb_0.y + cb_0.height),
        width: ((cb_3.x) - (bounds.x)),
        height: ((cb_2.y) - ((cb_0.y + cb_0.height))),
    };
    node.children.push(build_headerPanel(cb_0, Rc::clone(&state), label_bindings));
    node.children.push(build_functionKeys(cb_1, Rc::clone(&state), label_bindings));
    node.children.push(build_timeline(cb_2, Rc::clone(&state), label_bindings));
    node.children.push(build_imageSource(cb_3, Rc::clone(&state), label_bindings));
    node.children.push(build_textSource(cb_4, Rc::clone(&state), label_bindings));
    node.children.push(build_warningPanel(cb_5, Rc::clone(&state), label_bindings));
    node
}

// QML type: `Item` (id: `headerPanel`)
#[rustfmt::skip]
fn build_headerPanel(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Container::new(bounds)));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("headerPanel"),
    };
    let cb_0 = Rect {
        x: (((bounds.x + bounds.width / 2)) - (bounds.width) / 2),
        y: (((bounds.y + bounds.height / 2)) - (bounds.height) / 2),
        width: bounds.width,
        height: bounds.height,
    };
    let cb_1 = Rect {
        x: bounds.x + 0,
        y: bounds.y + 0,
        width: bounds.width,
        height: bounds.height,
    };
    let cb_2 = Rect {
        x: ((cb_0.x) - (bounds.width)),
        y: (((bounds.y + bounds.height / 2)) - (bounds.height) / 2),
        width: bounds.width,
        height: bounds.height,
    };
    let cb_3 = Rect {
        x: (((bounds.x + bounds.width)) - (bounds.width)),
        y: (((bounds.y + bounds.height / 2)) - (bounds.height) / 2),
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_textTime(cb_0, Rc::clone(&state), label_bindings));
    node.children.push(build_timer(cb_1, Rc::clone(&state), label_bindings));
    node.children.push(build_imgMute(cb_2, Rc::clone(&state), label_bindings));
    node.children.push(build_textTemperature(cb_3, Rc::clone(&state), label_bindings));
    node
}

// QML type: `Text` (id: `textTime`)
#[rustfmt::skip]
fn build_textTime(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Label::new("", bounds)));
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("textTime"),
    };
    node
}

// QML type: `Timer` (id: `timer`)
#[rustfmt::skip]
fn build_timer(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `Timer`
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Container::new(bounds)));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("timer"),
    };
    node
}

// QML type: `Image` (id: `imgMute`)
#[rustfmt::skip]
fn build_imgMute(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // QT-IMG: Image source → qt_assets::IMG_IMGMUTE (Images/ImgMute.png)
    let widget: Rc<RefCell<dyn Widget>> = qt_image(bounds, qt_assets::IMG_IMGMUTE);
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("imgMute"),
    };
    node
}

// QML type: `Text` (id: `textTemperature`)
#[rustfmt::skip]
fn build_textTemperature(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Label::new("15 °C", bounds)));
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("textTemperature"),
    };
    node
}

// QML type: `Item` (id: `functionKeys`)
#[rustfmt::skip]
fn build_functionKeys(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Container::new(bounds)));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("functionKeys"),
    };
    let cb_0 = Rect {
        x: (((bounds.x + bounds.width / 2)) - (300) / 2),
        y: bounds.y,
        width: 300,
        height: (((bounds.y + bounds.height)) - (bounds.y)),
    };
    let cb_1 = Rect {
        x: bounds.x,
        y: bounds.y,
        width: bounds.width,
        height: (((bounds.y + bounds.height)) - (bounds.y)),
    };
    let cb_2 = Rect {
        x: ((cb_1.x + cb_1.width) + 3),
        y: bounds.y,
        width: bounds.width,
        height: (((bounds.y + bounds.height)) - (bounds.y)),
    };
    let cb_3 = Rect {
        x: (((bounds.x + bounds.width)) - (bounds.width)),
        y: bounds.y,
        width: bounds.width,
        height: (((bounds.y + bounds.height)) - (bounds.y)),
    };
    node.children.push(build_rowButtons(cb_0, Rc::clone(&state), label_bindings));
    node.children.push(build_repeatBtn(cb_1, Rc::clone(&state), label_bindings));
    node.children.push(build_node_17(cb_2, Rc::clone(&state), label_bindings));
    node.children.push(build_node_18(cb_3, Rc::clone(&state), label_bindings));
    node
}

// QML type: `RowLayout` (id: `rowButtons`)
#[rustfmt::skip]
fn build_rowButtons(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `RowLayout`
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Container::new(bounds)));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("rowButtons"),
    };
    let child_bounds = Rect {
        x: bounds.x + 0,
        y: bounds.y + 0,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_repeaterButtons(child_bounds, Rc::clone(&state), label_bindings));
    node
}

// QML type: `Repeater` (id: `repeaterButtons`)
#[rustfmt::skip]
fn build_repeaterButtons(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `Repeater`
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Container::new(bounds)));
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("repeaterButtons"),
    };
    node
}

// QML type: `Button` (id: `repeatBtn`)
#[rustfmt::skip]
fn build_repeatBtn(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let mut button = Button::new("", bounds);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(button));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("repeatBtn"),
    };
    // QT-03c centerIn: parent (no explicit size — defaulted to parent bounds)
    let child_bounds = Rect {
        x: bounds.x + 0,
        y: bounds.y + 0,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_node_20(child_bounds, Rc::clone(&state), label_bindings));
    node
}

// QML type: `Image`
#[rustfmt::skip]
fn build_node_20(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // QT-IMG: Image source → qt_assets::IMG_IMGMEDIATRACKREPEAT_48 (Qml/Images/ImgMediaTrackRepeat_48.png)
    let widget: Rc<RefCell<dyn Widget>> = qt_image(bounds, qt_assets::IMG_IMGMEDIATRACKREPEAT_48);
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    };
    node
}

// QML type: `Button`
#[rustfmt::skip]
fn build_node_17(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let mut button = Button::new("", bounds);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(button));
    // emitter-skipped (QT-04c+): 4 property declaration(s)
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    };
    let child_bounds = bounds;
    node.children.push(build_shape(child_bounds, Rc::clone(&state), label_bindings));
    let child_bounds = bounds;
    node.children.push(build_node_22(child_bounds, Rc::clone(&state), label_bindings));
    node
}

// QML type: `Shape` (id: `shape`)
#[rustfmt::skip]
fn build_shape(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `Shape`
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Container::new(bounds)));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("shape"),
    };
    let child_bounds = Rect {
        x: bounds.x + 0,
        y: bounds.y + 0,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_shapePath(child_bounds, Rc::clone(&state), label_bindings));
    node
}

// QML type: `ShapePath` (id: `shapePath`)
#[rustfmt::skip]
fn build_shapePath(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `ShapePath`
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Container::new(bounds)));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("shapePath"),
    };
    let child_bounds = Rect {
        x: bounds.x + 0,
        y: bounds.y + 0,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_node_24(child_bounds, Rc::clone(&state), label_bindings));
    node
}

// QML type: `PathLine`
#[rustfmt::skip]
fn build_node_24(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `PathLine`
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Container::new(bounds)));
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    };
    node
}

// QML type: `Text`
#[rustfmt::skip]
fn build_node_22(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Label::new("", bounds)));
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    };
    node
}

// QML type: `Button`
#[rustfmt::skip]
fn build_node_18(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let mut button = Button::new("", bounds);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(button));
    // emitter-skipped (QT-04c+): 4 property declaration(s)
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    };
    // QT-03c centerIn: parent (no explicit size — defaulted to parent bounds)
    let child_bounds = Rect {
        x: bounds.x + 0,
        y: bounds.y + 0,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_node_25(child_bounds, Rc::clone(&state), label_bindings));
    node
}

// QML type: `Image`
#[rustfmt::skip]
fn build_node_25(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // QT-IMG: Image source → qt_assets::IMG_IMGSHUFFLEON_48 (Qml/Images/ImgShuffleOn_48.png)
    let widget: Rc<RefCell<dyn Widget>> = qt_image(bounds, qt_assets::IMG_IMGSHUFFLEON_48);
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    };
    node
}

// QML type: `Item` (id: `timeline`)
#[rustfmt::skip]
fn build_timeline(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Container::new(bounds)));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("timeline"),
    };
    let cb_0 = Rect {
        x: bounds.x + 0,
        y: bounds.y + 0,
        width: bounds.width,
        height: bounds.height,
    };
    let cb_1 = Rect {
        x: (((bounds.x + bounds.width / 2)) - (bounds.width) / 2),
        y: bounds.y,
        width: bounds.width,
        height: (((bounds.y + bounds.height)) - (bounds.y)),
    };
    let cb_2 = Rect {
        x: bounds.x,
        y: bounds.y,
        width: (((cb_1.x - 5)) - (bounds.x)),
        height: (((bounds.y + bounds.height)) - (bounds.y)),
    };
    let cb_3 = Rect {
        x: ((cb_1.x + cb_1.width) + 5),
        y: bounds.y,
        width: (((bounds.x + bounds.width)) - (((cb_1.x + cb_1.width) + 5))),
        height: (((bounds.y + bounds.height)) - (bounds.y)),
    };
    node.children.push(build_node_26(cb_0, Rc::clone(&state), label_bindings));
    node.children.push(build_timeSlider(cb_1, Rc::clone(&state), label_bindings));
    node.children.push(build_textPosition(cb_2, Rc::clone(&state), label_bindings));
    node.children.push(build_textElapsed(cb_3, Rc::clone(&state), label_bindings));
    node
}

// QML type: `Connections`
#[rustfmt::skip]
fn build_node_26(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `Connections`
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Container::new(bounds)));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    };
    node
}

// QML type: `Slider` (id: `timeSlider`)
#[rustfmt::skip]
fn build_timeSlider(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `Slider`
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Container::new(bounds)));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("timeSlider"),
    };
    node
}

// QML type: `Text` (id: `textPosition`)
#[rustfmt::skip]
fn build_textPosition(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Label::new("", bounds)));
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("textPosition"),
    };
    node
}

// QML type: `Text` (id: `textElapsed`)
#[rustfmt::skip]
fn build_textElapsed(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Label::new("", bounds)));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("textElapsed"),
    };
    node
}

// QML type: `Rectangle` (id: `imageSource`)
#[rustfmt::skip]
fn build_imageSource(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Container::new(bounds)));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("imageSource"),
    };
    // emitter-skipped (QT-03c+): anchors.top: parent.top
    // emitter-skipped (QT-03c+): anchors.left: parent.left
    // emitter-skipped (QT-03c+): anchors.right: parent.right
    // emitter-skipped (QT-03c+): anchors.bottom: parent.bottom
    let child_bounds = Rect {
        x: bounds.x + 0,
        y: bounds.y + 0,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_image(child_bounds, Rc::clone(&state), label_bindings));
    // emitter-skipped (QT-03c+): anchors.left: parent.left
    // emitter-skipped (QT-03c+): anchors.leftMargin: 10
    // emitter-skipped (QT-03c+): anchors.right: parent.right
    // emitter-skipped (QT-03c+): anchors.bottom: parent.bottom
    // emitter-skipped (QT-03c+): anchors.bottomMargin: 4
    let child_bounds = Rect {
        x: bounds.x + 0,
        y: bounds.y + 0,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_textCaption(child_bounds, Rc::clone(&state), label_bindings));
    node
}

// QML type: `Image` (id: `image`)
#[rustfmt::skip]
fn build_image(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // QT-IMG: Image with no resolvable source literal; emitting an empty container
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Container::new(bounds)));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("image"),
    };
    node
}

// QML type: `Text` (id: `textCaption`)
#[rustfmt::skip]
fn build_textCaption(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Label::new("", bounds)));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("textCaption"),
    };
    node
}

// QML type: `Text` (id: `textSource`)
#[rustfmt::skip]
fn build_textSource(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Label::new("", bounds)));
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("textSource"),
    };
    node
}

// QML type: `Item` (id: `warningPanel`)
#[rustfmt::skip]
fn build_warningPanel(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Container::new(bounds)));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("warningPanel"),
    };
    let cb_0 = Rect {
        x: bounds.x,
        y: bounds.y,
        width: 100,
        height: (((bounds.y + bounds.height)) - (bounds.y)),
    };
    let cb_1 = Rect {
        x: ((cb_0.x + cb_0.width) + 20),
        y: bounds.y,
        width: ((((bounds.x + bounds.width) - 10)) - (((cb_0.x + cb_0.width) + 20))),
        height: (((bounds.y + bounds.height)) - (bounds.y)),
    };
    node.children.push(build_busyIndicator(cb_0, Rc::clone(&state), label_bindings));
    node.children.push(build_textWarning(cb_1, Rc::clone(&state), label_bindings));
    node
}

// QML type: `BusyIndicator` (id: `busyIndicator`)
#[rustfmt::skip]
fn build_busyIndicator(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `BusyIndicator`
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Container::new(bounds)));
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("busyIndicator"),
    };
    node
}

// QML type: `Text` (id: `textWarning`)
#[rustfmt::skip]
fn build_textWarning(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Label::new("", bounds)));
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("textWarning"),
    };
    node
}

// QML type: `Rectangle`
#[rustfmt::skip]
fn build_node_3(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    let mut w = Container::new(bounds);
    // TODO QT-04e: bind color (non-literal QML expression)
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    };
    let child_bounds = bounds;
    node.children.push(build_node_34(child_bounds, Rc::clone(&state), label_bindings));
    node
}

// QML type: `MouseArea`
#[rustfmt::skip]
fn build_node_34(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    let mut click_area = ClickArea::new(bounds);
    // QT-04 body: scxmlBolero.submitEvent("Inp.App.Media.ModalOverlay.Clicked")
    click_area.set_on_click(|_b| {
        // TODO QT-04e: lower QML expression to Rust.
    });
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(click_area));
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    };
    node
}

// QML type: `Item` (id: `bottomPanel`)
#[rustfmt::skip]
fn build_bottomPanel(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Container::new(bounds)));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("bottomPanel"),
    };
    let child_bounds = bounds;
    node.children.push(build_rowButtons_35(child_bounds, Rc::clone(&state), label_bindings));
    node
}

// QML type: `RowLayout` (id: `rowButtons`)
#[rustfmt::skip]
fn build_rowButtons_35(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `RowLayout`
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Container::new(bounds)));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("rowButtons"),
    };
    let child_bounds = Rect {
        x: bounds.x + 0,
        y: bounds.y + 0,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_repeaterButtons_36(child_bounds, Rc::clone(&state), label_bindings));
    node
}

// QML type: `Repeater` (id: `repeaterButtons`)
#[rustfmt::skip]
fn build_repeaterButtons_36(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    label_bindings: &mut Vec<LabelBinding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `Repeater`
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(Container::new(bounds)));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("repeaterButtons"),
    };
    node
}
