// SPDX-License-Identifier: MIT
//
// Generated by `rlvgl-creator qt emit --target rlvgl` from `/Users/iraabbott/softoboros/ops/packer/submodules/scjson/tutorial/Examples/Qt/SkodaBoleroInfotainment/Qml/Media/FrameMedia.qml`.
// Do not edit by hand — regenerate with:
//   cargo run --features creator --bin rlvgl-creator -- \
//       qt emit --target rlvgl <input.qml> <out_dir>
//
// Emit-shape contract: docs/qt-support/03b-rlvgl-widget-mapping.md
// QT-03b notes:
//   * helper functions named per §8 (`build_<sanitized_id>` /
//     `build_node_<index>`) so reviewers have stable handles.
//   * bounds resolved per §7 trivial path; non-`fill`/`margins`
//     anchors are deferred to QT-03c.
//   * property lowering per §6; unsupported lower to TODOs.
// QT-04b notes (docs/qt-support/04b-properties-bindings.md):
//   * `pub struct ScreenState` carries every QML root-level
//     property declaration (see §3 / §5).
//   * `build_screen` returns `(WidgetNode, Rc<RefCell<ScreenState>>)`
//     and threads `state` through every helper.
//   * Handler bodies that match the §7 grammar lower to
//     `state.borrow_mut()...` mutations under a `// QT-04b body:`
//     marker; non-matching bodies fall through to `// QT-04 body:`.

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_variables)]

extern crate alloc;

use crate::qt_assets;
use alloc::rc::Rc;
use alloc::string::String;
use alloc::vec::Vec;
use core::cell::RefCell;

use media_player::Machine;
use rlvgl_core::WidgetNode;
use rlvgl_core::image::BlitOpts;
use rlvgl_core::widget::{Color, Rect, Widget};
use rlvgl_widgets::button::Button;
use rlvgl_widgets::click_area::ClickArea;
use rlvgl_widgets::container::Container;
use rlvgl_widgets::image::Image;
use rlvgl_widgets::label::Label;

/// rlvgl-target emit-shape version. Bumping is Specification-Required
/// (see `docs/qt-support/04b-properties-bindings.md` §11).
pub const QT_EMIT_VERSION: u32 = 19;

/// `qt-ir` schema version this module was generated from.
pub const QT_IR_VERSION: u32 = 2;

/// Source `.qml` file path as recorded at emit time.
pub const QT_SOURCE: &str = "/Users/iraabbott/softoboros/ops/packer/submodules/scjson/tutorial/Examples/Qt/SkodaBoleroInfotainment/Qml/Media/FrameMedia.qml";

/// QT-05 §6 linkage version. v2 is the istate M1P6 dynamic-string
/// surface (`step`/`is_active`/`get_var`), linked via `--scxml-context`.
pub const ISTATE_LINKAGE_VERSION: u32 = 2;

/// QT-05a §8 derived state-machine ID; matches the
/// `<sm>_gen` crate name stem (v1) or the `--scxml-context` crate (v2).
pub const QT_SM_NAME: &str = "media_player";

/// State threaded through every helper. One field per
/// QT-04b §5-supported property declared on the QML root.
/// `#[rustfmt::skip]` so the field order matches QT-01a's IR
/// declaration order rather than rustfmt's alphabetical sort.
#[rustfmt::skip]
#[derive(Debug, Clone)]
pub struct ScreenState {
    pub i_ROW_SPACING: i32,
    pub panelHeight: i32,
    pub repeatBtn_itemSelected: bool,
    pub repeatBtn_topBorderVisible: bool,
    pub repeatBtn_highlightBackgroundWhenSelected: bool,
    pub repeatBtn_gradientColor: String,
    pub shapePath_iOffset: i32,
    pub warningPanel_code: i32,
}

/// Reactive Label-text binding emitted by QT-04e §3. Each
/// entry pairs a concrete `Rc<RefCell<Label>>` with an
/// accessor that reads the bound state field. Use
/// [`refresh_bindings`] to re-apply every binding in one call.
pub struct LabelBinding {
    pub label: Rc<RefCell<Label>>,
    pub accessor: fn(&ScreenState) -> String,
}

impl LabelBinding {
    /// Re-apply this binding from the supplied state.
    pub fn refresh(&self, state: &ScreenState) {
        self.label.borrow_mut().set_text((self.accessor)(state));
    }
}

/// QT-05g §3 — a decoded, magenta-keyed, `'static`-leaked artwork
/// buffer plus its natural dimensions.
#[derive(Clone, Copy)]
pub struct ImageArt {
    pub width: i32,
    pub height: i32,
    pub pixels: &'static [Color],
}

/// QT-05g §3 — reactive `Image`-source binding. Shows `on` when the
/// bound state is active, else `off`. `state_id` is the QML predicate
/// passed through verbatim to `Machine::is_active` (authority: derive).
pub struct PredicateBinding {
    pub image: Rc<RefCell<Image<'static>>>,
    pub state_id: &'static str,
    pub on: ImageArt,
    pub off: ImageArt,
}

impl PredicateBinding {
    /// Re-apply this binding from the supplied machine.
    pub fn refresh(&self, machine: &Machine) {
        let art = if machine.is_active(self.state_id) {
            &self.on
        } else {
            &self.off
        };
        self.image
            .borrow_mut()
            .set_pixels(art.width, art.height, art.pixels);
    }
}

/// QT-05h §3 — reactive `Image`-visibility binding driven by
/// `Machine::is_active`. `state_id` is the QML predicate passed
/// through verbatim (authority: derive).
pub struct VisibilityBinding {
    pub image: Rc<RefCell<Image<'static>>>,
    pub state_id: &'static str,
}

impl VisibilityBinding {
    /// Hide the Image when the bound state is inactive, else show it.
    pub fn refresh(&self, machine: &Machine) {
        self.image
            .borrow_mut()
            .set_hidden(!machine.is_active(self.state_id));
    }
}

/// QT-05g §3 / QT-05h §3 — sealed enum over the binding sources
/// reactive `refresh_bindings` knows how to drive.
pub enum Binding {
    Label(LabelBinding),
    Predicate(PredicateBinding),
    Visibility(VisibilityBinding),
}

/// Build the screen widget tree at `bounds` and return it
/// alongside the `ScreenState` handle (QT-04b §3), the
/// `Rc<RefCell<Machine>>` istate (linkage v2) handle, and the
/// `Vec<Binding>` of reactive bindings (QT-05g §3). Callers
/// drive the machine via `machine.borrow_mut().step("…", …)`
/// and call `refresh_bindings` to re-apply state-predicate
/// artwork (e.g. Play↔Pause via `is_active`).
#[rustfmt::skip]
pub fn build_screen(
    bounds: Rect,
) -> (WidgetNode, Rc<RefCell<ScreenState>>, Rc<RefCell<Machine>>, Vec<Binding>) {
    let state = Rc::new(RefCell::new(ScreenState {
        i_ROW_SPACING: 3,
        // QT-04b: non-literal default for `panelHeight`: height / 6 - AppConsts.i_DISPLAY_PADDING
        panelHeight: 0,
        repeatBtn_itemSelected: false,
        repeatBtn_topBorderVisible: true,
        repeatBtn_highlightBackgroundWhenSelected: false,
        // QT-04b: non-literal default for `gradientColor`: AppConsts.cl_ITEM_COLOR
        repeatBtn_gradientColor: String::new(),
        shapePath_iOffset: 7,
        // QT-04b: non-literal default for `code`: getCode()
        warningPanel_code: 0,
    }));
    let machine = Rc::new(RefCell::new({ let mut m = Machine::new(); m.start(); m }));
    let mut bindings: Vec<Binding> = Vec::new();
    let node = build_pane(bounds, Rc::clone(&state), Rc::clone(&machine), &mut bindings);
    (node, state, machine, bindings)
}

/// Re-apply every QT-04e / QT-05g / QT-05h binding from the
/// current state and machine. Idempotent; safe to call after any
/// `machine.step(…)`. No-op when `bindings` is empty.
#[rustfmt::skip]
pub fn refresh_bindings(state: &Rc<RefCell<ScreenState>>, machine: &Rc<RefCell<Machine>>, bindings: &[Binding]) {
    let s = state.borrow();
    let m = machine.borrow();
    for b in bindings {
        match b {
                         Binding::Label(lb) => lb.refresh(&s),
                         Binding::Predicate(pb) => pb.refresh(&m),
                         Binding::Visibility(vb) => vb.refresh(&m),
    }
    }
}

// Required `qt_assets` symbols (one RLE `&[u8]` blob each):
//   qt_assets::IMG_IMGBOLEROBACKGROUND  ←  Images/ImgBoleroBackground.png
//   qt_assets::IMG_IMGMUTE  ←  Images/ImgMute.png
//   qt_assets::IMG_IMGREWINDBACK_48  ←  Qml/Images/ImgRewindBack_48.png
//   qt_assets::IMG_IMGPAUSE_48  ←  Qml/Images/ImgPause_48.png
//   qt_assets::IMG_IMGPLAY_48  ←  Qml/Images/ImgPlay_48.png
//   qt_assets::IMG_IMGREWINDFORWARD_48  ←  Qml/Images/ImgRewindForward_48.png
//   qt_assets::IMG_IMGMEDIATRACKREPEAT_48  ←  Qml/Images/ImgMediaTrackRepeat_48.png
//   qt_assets::IMG_IMGSHUFFLEON_48  ←  Qml/Images/ImgShuffleOn_48.png
//   qt_assets::IMG_IMGSHUFFLEOFF_48  ←  Qml/Images/ImgShuffleOff_48.png
/// Decode a vendored RLE asset into an owned, leaked pixel buffer and
/// wrap it in an `Image` widget (see emit-time docs above).
#[rustfmt::skip]
fn qt_image(bounds: Rect, rle: &'static [u8]) -> Rc<RefCell<dyn Widget>> {
    let (w, h, palette_bytes, stream) =
        rlvgl_decomp::parse_rle_blob(rle).expect("qt_image: malformed RLE asset");
    let palette_len = palette_bytes.len() / 2;
    let mut palette = alloc::vec![0u16; palette_len];
    for i in 0..palette_len {
        palette[i] = u16::from_le_bytes([palette_bytes[i * 2], palette_bytes[i * 2 + 1]]);
    }
    let rgba = rlvgl_decomp::decode_rgba(w as usize, h as usize, &palette, stream)
        .expect("qt_image: RLE decode failed");
    let pixels: Vec<Color> = rgba
        .chunks_exact(4)
        .map(|c| if c[0] == 0xFF && c[1] == 0x00 && c[2] == 0xFF {
            Color(0x00, 0x00, 0x00, 0x00) // magenta sentinel → transparent (RGB565 has no alpha)
        } else {
            Color(c[0], c[1], c[2], c[3])
        })
        .collect();
    let pixels: &'static [Color] = Vec::leak(pixels);
    let mut img = Image::new(bounds, w as i32, h as i32, pixels);
    // An Image paints its own pixels; the widget background MUST be
    // transparent so the default opaque-white `Style` does not bury
    // the artwork (and content drawn behind it).
    img.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    // QML's default `fillMode` is `Image.Stretch`: scale the source to
    // fill the destination bounds. `scale` is 8.8 fixed-point, so 256 =
    // 1:1; dest/src * 256 stretches source pixels across `bounds`.
    let scale_x = if w > 0 {
        ((bounds.width.max(0) as i64 * 256 / w as i64).clamp(1, 0xffff)) as u16
    } else { 256 };
    let scale_y = if h > 0 {
        ((bounds.height.max(0) as i64 * 256 / h as i64).clamp(1, 0xffff)) as u16
    } else { 256 };
    let img = img.with_blit_opts(BlitOpts { scale_x, scale_y, ..BlitOpts::default() });
    Rc::new(RefCell::new(img))
}

/// QT-05g: decode one vendored RLE asset into a leaked `ImageArt`
/// (magenta-keyed → transparent, RGB565 has no alpha).
#[rustfmt::skip]
fn qt_image_art(rle: &'static [u8]) -> ImageArt {
    let (w, h, palette_bytes, stream) =
        rlvgl_decomp::parse_rle_blob(rle).expect("qt_image_art: malformed RLE asset");
    let palette_len = palette_bytes.len() / 2;
    let mut palette = alloc::vec![0u16; palette_len];
    for i in 0..palette_len {
        palette[i] = u16::from_le_bytes([palette_bytes[i * 2], palette_bytes[i * 2 + 1]]);
    }
    let rgba = rlvgl_decomp::decode_rgba(w as usize, h as usize, &palette, stream)
        .expect("qt_image_art: RLE decode failed");
    let pixels: Vec<Color> = rgba
        .chunks_exact(4)
        .map(|c| if c[0] == 0xFF && c[1] == 0x00 && c[2] == 0xFF {
            Color(0x00, 0x00, 0x00, 0x00)
        } else {
            Color(c[0], c[1], c[2], c[3])
        })
        .collect();
    let pixels: &'static [Color] = Vec::leak(pixels);
    ImageArt { width: w as i32, height: h as i32, pixels }
}

/// QT-05g: build a predicate-bound Image. Decodes both branches, builds
/// the Image at the machine-driven branch, and returns it as a
/// `dyn Widget` plus the `Binding::Predicate` that swaps it on refresh.
#[rustfmt::skip]
fn qt_predicate_image(
    bounds: Rect,
    on_rle: &'static [u8],
    off_rle: &'static [u8],
    state_id: &'static str,
    active: bool,
) -> (Rc<RefCell<dyn Widget>>, Binding) {
    let on = qt_image_art(on_rle);
    let off = qt_image_art(off_rle);
    let cur = if active { on } else { off };
    let mut img = Image::new(bounds, cur.width, cur.height, cur.pixels);
    img.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    // QML default `Image.Stretch`: scale source → bounds (8.8 fixed-point).
    let scale_x = if cur.width > 0 {
        ((bounds.width.max(0) as i64 * 256 / cur.width as i64).clamp(1, 0xffff)) as u16
    } else { 256 };
    let scale_y = if cur.height > 0 {
        ((bounds.height.max(0) as i64 * 256 / cur.height as i64).clamp(1, 0xffff)) as u16
    } else { 256 };
    let img = img.with_blit_opts(BlitOpts { scale_x, scale_y, ..BlitOpts::default() });
    let image = Rc::new(RefCell::new(img));
    let widget: Rc<RefCell<dyn Widget>> = image.clone();
    (widget, Binding::Predicate(PredicateBinding { image, state_id, on, off }))
}

/// QT-05h: build a visibility-bound Image. Decodes the source, builds
/// the Image (initially hidden iff the bound state is inactive), and
/// returns it as a `dyn Widget` plus its `Binding::Visibility`.
#[rustfmt::skip]
fn qt_visibility_image(
    bounds: Rect,
    rle: &'static [u8],
    state_id: &'static str,
    visible: bool,
) -> (Rc<RefCell<dyn Widget>>, Binding) {
    let art = qt_image_art(rle);
    let mut img = Image::new(bounds, art.width, art.height, art.pixels);
    img.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let scale_x = if art.width > 0 {
        ((bounds.width.max(0) as i64 * 256 / art.width as i64).clamp(1, 0xffff)) as u16
    } else { 256 };
    let scale_y = if art.height > 0 {
        ((bounds.height.max(0) as i64 * 256 / art.height as i64).clamp(1, 0xffff)) as u16
    } else { 256 };
    let mut img = img.with_blit_opts(BlitOpts { scale_x, scale_y, ..BlitOpts::default() });
    img.set_hidden(!visible);
    let image = Rc::new(RefCell::new(img));
    let widget: Rc<RefCell<dyn Widget>> = image.clone();
    (widget, Binding::Visibility(VisibilityBinding { image, state_id }))
}

/// Construct a `Label` with a transparent background (QML text has
/// no fill), so it does not paint the opaque-white default `Style`.
fn qt_label(text: impl Into<String>, bounds: Rect) -> Label {
    let mut l = Label::new(text, bounds);
    l.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    l
}

// QML type: `Image` (id: `pane`)
#[rustfmt::skip]
fn build_pane(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // QT-IMG: Image source → qt_assets::IMG_IMGBOLEROBACKGROUND (Images/ImgBoleroBackground.png)
    let widget: Rc<RefCell<dyn Widget>> = qt_image(bounds, qt_assets::IMG_IMGBOLEROBACKGROUND);
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("pane"),
    };
    let child_bounds = bounds;
    node.children.push(build_paneMouseArea(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `MouseArea` (id: `paneMouseArea`)
#[rustfmt::skip]
fn build_paneMouseArea(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    let mut click_area = ClickArea::new(bounds);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(click_area));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("paneMouseArea"),
    };
    let cb_2 = Rect {
        x: (bounds.x + 8),
        y: ((((bounds.y + bounds.height) - 8)) - ((((bounds.height / 6) - 8)))),
        width: ((((bounds.x + bounds.width) - 8)) - ((bounds.x + 8))),
        height: (((bounds.height / 6) - 8)),
    };
    let cb_0 = Rect {
        x: (bounds.x + 8),
        y: (bounds.y + 8),
        width: ((((bounds.x + bounds.width) - 8)) - ((bounds.x + 8))),
        height: ((cb_2.y) - ((bounds.y + 8))),
    };
    let cb_1 = Rect {
        x: bounds.x,
        y: bounds.y,
        width: (((bounds.x + bounds.width)) - (bounds.x)),
        height: (((bounds.y + bounds.height)) - (bounds.y)),
    };
    node.children.push(build_contentPaddingItem(cb_0, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_node_3(cb_1, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_bottomPanel(cb_2, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `Item` (id: `contentPaddingItem`)
#[rustfmt::skip]
fn build_contentPaddingItem(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("contentPaddingItem"),
    };
    let cb_0 = Rect {
        x: bounds.x,
        y: bounds.y,
        width: (((bounds.x + bounds.width)) - (bounds.x)),
        height: 36,
    };
    let cb_1 = Rect {
        x: bounds.x,
        y: ((((bounds.y + bounds.height) - 10)) - ((((bounds.height / 6) - 8)))),
        width: (((bounds.x + bounds.width)) - (bounds.x)),
        height: (((bounds.height / 6) - 8)),
    };
    let cb_3 = Rect {
        x: (((bounds.x + bounds.width)) - (160)),
        y: (cb_0.y + cb_0.height),
        width: 160,
        height: 160,
    };
    let cb_2 = Rect {
        x: bounds.x,
        y: (cb_3.y + cb_3.height),
        width: (((bounds.x + bounds.width)) - (bounds.x)),
        height: ((cb_1.y) - ((cb_3.y + cb_3.height))),
    };
    let cb_4 = Rect {
        x: (bounds.x + 10),
        y: cb_3.y,
        width: (((cb_3.x - 10)) - ((bounds.x + 10))),
        height: (((cb_3.y + cb_3.height)) - (cb_3.y)),
    };
    let cb_5 = Rect {
        x: bounds.x,
        y: (cb_0.y + cb_0.height),
        width: ((cb_3.x) - (bounds.x)),
        height: ((cb_2.y) - ((cb_0.y + cb_0.height))),
    };
    node.children.push(build_headerPanel(cb_0, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_functionKeys(cb_1, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_timeline(cb_2, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_imageSource(cb_3, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_textSource(cb_4, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_warningPanel(cb_5, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `Item` (id: `headerPanel`)
#[rustfmt::skip]
fn build_headerPanel(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("headerPanel"),
    };
    let cb_0 = Rect {
        x: (((bounds.x + bounds.width / 2)) - (bounds.width) / 2),
        y: (((bounds.y + bounds.height / 2)) - (bounds.height) / 2),
        width: bounds.width,
        height: bounds.height,
    };
    let cb_1 = Rect {
        x: bounds.x + 0,
        y: bounds.y + 0,
        width: bounds.width,
        height: bounds.height,
    };
    let cb_2 = Rect {
        x: ((cb_0.x) - (32)),
        y: (((bounds.y + bounds.height / 2)) - (32) / 2),
        width: 32,
        height: 32,
    };
    let cb_3 = Rect {
        x: (((bounds.x + bounds.width)) - (bounds.width)),
        y: (((bounds.y + bounds.height / 2)) - (bounds.height) / 2),
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_textTime(cb_0, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_timer(cb_1, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_imgMute(cb_2, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_textTemperature(cb_3, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `Text` (id: `textTime`)
#[rustfmt::skip]
fn build_textTime(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(qt_label("", bounds)));
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("textTime"),
    };
    node
}

// QML type: `Timer` (id: `timer`)
#[rustfmt::skip]
fn build_timer(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `Timer`
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("timer"),
    };
    node
}

// QML type: `Image` (id: `imgMute`)
#[rustfmt::skip]
fn build_imgMute(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // QT-05h visibility-bound: visible → scxmlBolero.muteOn (source IMG_IMGMUTE)
    let visible = machine.borrow().is_active("muteOn");
    let (widget, __vb): (Rc<RefCell<dyn Widget>>, Binding) =
        qt_visibility_image(bounds, qt_assets::IMG_IMGMUTE, "muteOn", visible);
    bindings.push(__vb);
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("imgMute"),
    };
    node
}

// QML type: `Text` (id: `textTemperature`)
#[rustfmt::skip]
fn build_textTemperature(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(qt_label("15 °C", bounds)));
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("textTemperature"),
    };
    node
}

// QML type: `Item` (id: `functionKeys`)
#[rustfmt::skip]
fn build_functionKeys(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("functionKeys"),
    };
    let cb_0 = Rect {
        x: (((bounds.x + bounds.width / 2)) - (300) / 2),
        y: bounds.y,
        width: 300,
        height: (((bounds.y + bounds.height)) - (bounds.y)),
    };
    let cb_1 = Rect {
        x: bounds.x,
        y: bounds.y,
        width: 65,
        height: (((bounds.y + bounds.height)) - (bounds.y)),
    };
    let cb_2 = Rect {
        x: ((cb_1.x + cb_1.width) + 3),
        y: bounds.y,
        width: 65,
        height: (((bounds.y + bounds.height)) - (bounds.y)),
    };
    let cb_3 = Rect {
        x: (((bounds.x + bounds.width)) - (65)),
        y: bounds.y,
        width: 65,
        height: (((bounds.y + bounds.height)) - (bounds.y)),
    };
    node.children.push(build_rowButtons(cb_0, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_repeatBtn(cb_1, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_node_17(cb_2, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_node_18(cb_3, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `RowLayout` (id: `rowButtons`)
#[rustfmt::skip]
fn build_rowButtons(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `RowLayout`
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("rowButtons"),
    };
    let child_bounds = Rect {
        x: bounds.x + 0,
        y: bounds.y + 0,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_repeaterButtons(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `Repeater` (id: `repeaterButtons`)
#[rustfmt::skip]
fn build_repeaterButtons(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `Repeater`
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("repeaterButtons"),
    };
    let cb_0 = Rect {
        x: (bounds.x + 75),
        y: (((bounds.y + bounds.height / 2)) - (48) / 2),
        width: 48,
        height: 48,
    };
    let cb_1 = Rect {
        x: ((cb_0.x + cb_0.width) + 3),
        y: (((bounds.y + bounds.height / 2)) - (48) / 2),
        width: 48,
        height: 48,
    };
    let cb_2 = Rect {
        x: ((cb_1.x + cb_1.width) + 3),
        y: (((bounds.y + bounds.height / 2)) - (48) / 2),
        width: 48,
        height: 48,
    };
    node.children.push(build___rep_btn_0(cb_0, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build___rep_btn_1(cb_1, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build___rep_btn_2(cb_2, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `Image` (id: `__rep_btn_0`)
#[rustfmt::skip]
fn build___rep_btn_0(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // QT-IMG: Image source → qt_assets::IMG_IMGREWINDBACK_48 (Qml/Images/ImgRewindBack_48.png)
    let widget: Rc<RefCell<dyn Widget>> = qt_image(bounds, qt_assets::IMG_IMGREWINDBACK_48);
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("__rep_btn_0"),
    };
    node
}

// QML type: `Image` (id: `__rep_btn_1`)
#[rustfmt::skip]
fn build___rep_btn_1(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // QT-05g predicate-bound: source → scxmlBolero.mediaPlaying ? on=IMG_IMGPAUSE_48 : off=IMG_IMGPLAY_48
    let active = machine.borrow().is_active("mediaPlaying");
    let (widget, __pb): (Rc<RefCell<dyn Widget>>, Binding) =
        qt_predicate_image(bounds, qt_assets::IMG_IMGPAUSE_48, qt_assets::IMG_IMGPLAY_48, "mediaPlaying", active);
    bindings.push(__pb);
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("__rep_btn_1"),
    };
    node
}

// QML type: `Image` (id: `__rep_btn_2`)
#[rustfmt::skip]
fn build___rep_btn_2(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // QT-IMG: Image source → qt_assets::IMG_IMGREWINDFORWARD_48 (Qml/Images/ImgRewindForward_48.png)
    let widget: Rc<RefCell<dyn Widget>> = qt_image(bounds, qt_assets::IMG_IMGREWINDFORWARD_48);
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("__rep_btn_2"),
    };
    node
}

// QML type: `Button` (id: `repeatBtn`)
#[rustfmt::skip]
fn build_repeatBtn(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let mut button = Button::new("", bounds);
    button.style_mut().bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(button));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("repeatBtn"),
    };
    // QT-03c centerIn: parent (no explicit size — defaulted to parent bounds)
    let child_bounds = Rect {
        x: bounds.x + 0,
        y: bounds.y + 0,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_node_23(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `Image`
#[rustfmt::skip]
fn build_node_23(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // QT-IMG: Image source → qt_assets::IMG_IMGMEDIATRACKREPEAT_48 (Qml/Images/ImgMediaTrackRepeat_48.png)
    let widget: Rc<RefCell<dyn Widget>> = qt_image(bounds, qt_assets::IMG_IMGMEDIATRACKREPEAT_48);
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    };
    node
}

// QML type: `Button`
#[rustfmt::skip]
fn build_node_17(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let mut button = Button::new("", bounds);
    button.style_mut().bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(button));
    // emitter-skipped (QT-04c+): 4 property declaration(s)
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    };
    let child_bounds = bounds;
    node.children.push(build_shape(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    let child_bounds = bounds;
    node.children.push(build_node_25(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `Shape` (id: `shape`)
#[rustfmt::skip]
fn build_shape(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `Shape`
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("shape"),
    };
    let child_bounds = Rect {
        x: bounds.x + 0,
        y: bounds.y + 0,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_shapePath(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `ShapePath` (id: `shapePath`)
#[rustfmt::skip]
fn build_shapePath(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `ShapePath`
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("shapePath"),
    };
    let child_bounds = Rect {
        x: bounds.x + 0,
        y: bounds.y + 0,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_node_27(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `PathLine`
#[rustfmt::skip]
fn build_node_27(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `PathLine`
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    };
    node
}

// QML type: `Text`
#[rustfmt::skip]
fn build_node_25(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(qt_label("", bounds)));
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    };
    node
}

// QML type: `Button`
#[rustfmt::skip]
fn build_node_18(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let mut button = Button::new("", bounds);
    button.style_mut().bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(button));
    // emitter-skipped (QT-04c+): 4 property declaration(s)
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    };
    // QT-03c centerIn: parent (no explicit size — defaulted to parent bounds)
    let child_bounds = Rect {
        x: bounds.x + 0,
        y: bounds.y + 0,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_node_28(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `Image`
#[rustfmt::skip]
fn build_node_28(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // QT-05g predicate-bound: source → scxmlBolero.mediaPlayMixModeOn ? on=IMG_IMGSHUFFLEON_48 : off=IMG_IMGSHUFFLEOFF_48
    let active = machine.borrow().is_active("mediaPlayMixModeOn");
    let (widget, __pb): (Rc<RefCell<dyn Widget>>, Binding) =
        qt_predicate_image(bounds, qt_assets::IMG_IMGSHUFFLEON_48, qt_assets::IMG_IMGSHUFFLEOFF_48, "mediaPlayMixModeOn", active);
    bindings.push(__pb);
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    };
    node
}

// QML type: `Item` (id: `timeline`)
#[rustfmt::skip]
fn build_timeline(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("timeline"),
    };
    let cb_0 = Rect {
        x: bounds.x + 0,
        y: bounds.y + 0,
        width: bounds.width,
        height: bounds.height,
    };
    let cb_1 = Rect {
        x: (((bounds.x + bounds.width / 2)) - ((bounds.width * 1)) / 2),
        y: bounds.y,
        width: (bounds.width * 1),
        height: (((bounds.y + bounds.height)) - (bounds.y)),
    };
    let cb_2 = Rect {
        x: bounds.x,
        y: bounds.y,
        width: (((cb_1.x - 5)) - (bounds.x)),
        height: (((bounds.y + bounds.height)) - (bounds.y)),
    };
    let cb_3 = Rect {
        x: ((cb_1.x + cb_1.width) + 5),
        y: bounds.y,
        width: (((bounds.x + bounds.width)) - (((cb_1.x + cb_1.width) + 5))),
        height: (((bounds.y + bounds.height)) - (bounds.y)),
    };
    node.children.push(build_node_29(cb_0, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_timeSlider(cb_1, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_textPosition(cb_2, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_textElapsed(cb_3, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `Connections`
#[rustfmt::skip]
fn build_node_29(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `Connections`
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    };
    node
}

// QML type: `Slider` (id: `timeSlider`)
#[rustfmt::skip]
fn build_timeSlider(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `Slider`
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("timeSlider"),
    };
    node
}

// QML type: `Text` (id: `textPosition`)
#[rustfmt::skip]
fn build_textPosition(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(qt_label("", bounds)));
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("textPosition"),
    };
    node
}

// QML type: `Text` (id: `textElapsed`)
#[rustfmt::skip]
fn build_textElapsed(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(qt_label("", bounds)));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("textElapsed"),
    };
    node
}

// QML type: `Rectangle` (id: `imageSource`)
#[rustfmt::skip]
fn build_imageSource(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("imageSource"),
    };
    // emitter-skipped (QT-03c+): anchors.top: parent.top
    // emitter-skipped (QT-03c+): anchors.left: parent.left
    // emitter-skipped (QT-03c+): anchors.right: parent.right
    // emitter-skipped (QT-03c+): anchors.bottom: parent.bottom
    let child_bounds = Rect {
        x: bounds.x + 0,
        y: bounds.y + 0,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_image(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    // emitter-skipped (QT-03c+): anchors.left: parent.left
    // emitter-skipped (QT-03c+): anchors.leftMargin: 10
    // emitter-skipped (QT-03c+): anchors.right: parent.right
    // emitter-skipped (QT-03c+): anchors.bottom: parent.bottom
    // emitter-skipped (QT-03c+): anchors.bottomMargin: 4
    let child_bounds = Rect {
        x: bounds.x + 0,
        y: bounds.y + 0,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_textCaption(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `Image` (id: `image`)
#[rustfmt::skip]
fn build_image(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // QT-IMG: Image with no resolvable source literal; emitting an empty transparent container
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("image"),
    };
    node
}

// QML type: `Text` (id: `textCaption`)
#[rustfmt::skip]
fn build_textCaption(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(qt_label("", bounds)));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("textCaption"),
    };
    node
}

// QML type: `Text` (id: `textSource`)
#[rustfmt::skip]
fn build_textSource(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(qt_label("", bounds)));
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("textSource"),
    };
    node
}

// QML type: `Item` (id: `warningPanel`)
#[rustfmt::skip]
fn build_warningPanel(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("warningPanel"),
    };
    let cb_0 = Rect {
        x: bounds.x,
        y: bounds.y,
        width: 100,
        height: (((bounds.y + bounds.height)) - (bounds.y)),
    };
    let cb_1 = Rect {
        x: ((cb_0.x + cb_0.width) + 20),
        y: bounds.y,
        width: ((((bounds.x + bounds.width) - 10)) - (((cb_0.x + cb_0.width) + 20))),
        height: (((bounds.y + bounds.height)) - (bounds.y)),
    };
    node.children.push(build_busyIndicator(cb_0, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_textWarning(cb_1, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `BusyIndicator` (id: `busyIndicator`)
#[rustfmt::skip]
fn build_busyIndicator(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `BusyIndicator`
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("busyIndicator"),
    };
    node
}

// QML type: `Text` (id: `textWarning`)
#[rustfmt::skip]
fn build_textWarning(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(qt_label("", bounds)));
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("textWarning"),
    };
    node
}

// QML type: `Rectangle`
#[rustfmt::skip]
fn build_node_3(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    let mut w = Container::new(bounds);
    // TODO QT-04e: bind color (non-literal QML expression)
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    };
    let child_bounds = bounds;
    node.children.push(build_node_37(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `MouseArea`
#[rustfmt::skip]
fn build_node_37(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    let mut click_area = ClickArea::new(bounds);
    // QT-04 body: scxmlBolero.submitEvent("Inp.App.Media.ModalOverlay.Clicked")
    click_area.set_on_click(|_b| {
        // TODO QT-04e: lower QML expression to Rust.
    });
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(click_area));
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    };
    node
}

// QML type: `Item` (id: `bottomPanel`)
#[rustfmt::skip]
fn build_bottomPanel(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("bottomPanel"),
    };
    let child_bounds = bounds;
    node.children.push(build_rowButtons_38(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `RowLayout` (id: `rowButtons`)
#[rustfmt::skip]
fn build_rowButtons_38(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `RowLayout`
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("rowButtons"),
    };
    let child_bounds = Rect {
        x: bounds.x + 0,
        y: bounds.y + 0,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_repeaterButtons_39(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `Repeater` (id: `repeaterButtons`)
#[rustfmt::skip]
fn build_repeaterButtons_39(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut Vec<Binding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `Repeater`
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("repeaterButtons"),
    };
    node
}
