// SPDX-License-Identifier: MIT
//
// Generated by `rlvgl-creator qt emit --target rlvgl` from `vendor/scjson/tutorial/Examples/Qt/SkodaBoleroInfotainment/Qml/Media/FrameMedia.qml`.
// Do not edit by hand — regenerate with:
//   cargo run --features creator --bin rlvgl-creator -- \
//       qt emit --target rlvgl <input.qml> <out_dir>
//
// Emit-shape contract: docs/qt-support/03b-rlvgl-widget-mapping.md
// QT-03b notes:
//   * helper functions named per §8 (`build_<sanitized_id>` /
//     `build_node_<index>`) so reviewers have stable handles.
//   * bounds resolved per §7 trivial path; non-`fill`/`margins`
//     anchors are deferred to QT-03c.
//   * property lowering per §6; unsupported lower to TODOs.
// QT-04b notes (docs/qt-support/04b-properties-bindings.md):
//   * `pub struct ScreenState` carries every QML root-level
//     property declaration (see §3 / §5).
//   * `build_screen` returns `(WidgetNode, Rc<RefCell<ScreenState>>)`
//     and threads `state` through every helper.
//   * Handler bodies that match the §7 grammar lower to
//     `state.borrow_mut()...` mutations under a `// QT-04b body:`
//     marker; non-matching bodies fall through to `// QT-04 body:`.

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_variables)]

extern crate alloc;

use crate::qt_assets;
use alloc::rc::Rc;
use alloc::string::String;
use alloc::vec::Vec;
use core::cell::RefCell;

use media_player::Machine;
use rlvgl_core::WidgetNode;
use rlvgl_core::image::BlitOpts;
use rlvgl_core::widget::{Color, Rect, Widget};
use rlvgl_widgets::button::Button;
use rlvgl_widgets::click_area::ClickArea;
use rlvgl_widgets::container::Container;
use rlvgl_widgets::image::Image;
use rlvgl_widgets::label::Label;

/// rlvgl-target emit-shape version. Bumping is Specification-Required
/// (see `docs/qt-support/04b-properties-bindings.md` §11).
pub const QT_EMIT_VERSION: u32 = 23;

/// `qt-ir` schema version this module was generated from.
pub const QT_IR_VERSION: u32 = 2;

/// Source `.qml` file path as recorded at emit time.
#[rustfmt::skip]
pub const QT_SOURCE: &str = "vendor/scjson/tutorial/Examples/Qt/SkodaBoleroInfotainment/Qml/Media/FrameMedia.qml";

/// QT-05 §6 linkage version. v2 is the istate M1P6 dynamic-string
/// surface (`step`/`is_active`/`get_var`), linked via `--scxml-context`.
pub const ISTATE_LINKAGE_VERSION: u32 = 2;

/// QT-05a §8 derived state-machine ID; matches the
/// `<sm>_gen` crate name stem (v1) or the `--scxml-context` crate (v2).
pub const QT_SM_NAME: &str = "media_player";

/// QT-05j — tap targets lowered from `submitBtnSetupEvent("…")` button
/// handlers: `(node tag, raw QML button-event)`. The consumer maps each
/// QML event to a machine event via `machine.step(…)`.
pub const BUTTON_TAP_EVENTS: &[(&str, &str)] = &[
    ("__rep_btn_0", "MediaFunc.Reverse"),
    ("__rep_btn_1", "MediaFunc.Play"),
    ("__rep_btn_2", "MediaFunc.Forward"),
    ("repeatBtn", "MediaFunc.Repeat"),
    ("__btn_mediafunc_scan", "MediaFunc.Scan"),
    ("__btn_mediafunc_shuffle", "MediaFunc.Shuffle"),
];

/// QT-05k — external-text targets lowered from Label `text: <obj>.<prop>`
/// sources: `(node tag, verbatim external key)`. The consumer resolves
/// each key to a string via `apply_external_text`.
#[rustfmt::skip]
pub const EXTERNAL_TEXT_BINDINGS: &[(&str, &str)] = &[
    ("textSource", "audioPlayer.currentPlayUrlFileName"),
];

/// State threaded through every helper. One field per
/// QT-04b §5-supported property declared on the QML root.
/// `#[rustfmt::skip]` so the field order matches QT-01a's IR
/// declaration order rather than rustfmt's alphabetical sort.
#[rustfmt::skip]
#[derive(Debug, Clone)]
pub struct ScreenState {
    pub i_row_spacing: i32,
    pub panel_height: i32,
    pub repeat_btn_item_selected: bool,
    pub repeat_btn_top_border_visible: bool,
    pub repeat_btn_highlight_background_when_selected: bool,
    pub repeat_btn_gradient_color: String,
    pub btn_mediafunc_scan_item_selected: bool,
    pub btn_mediafunc_scan_top_border_visible: bool,
    pub btn_mediafunc_scan_highlight_background_when_selected: bool,
    pub btn_mediafunc_scan_gradient_color: String,
    pub shape_path_i_offset: i32,
    pub btn_mediafunc_shuffle_item_selected: bool,
    pub btn_mediafunc_shuffle_top_border_visible: bool,
    pub btn_mediafunc_shuffle_highlight_background_when_selected: bool,
    pub btn_mediafunc_shuffle_gradient_color: String,
    pub warning_panel_code: i32,
}

/// Reactive Label-text binding emitted by QT-04e §3. Each
/// entry pairs a concrete `Rc<RefCell<Label>>` with an
/// accessor that reads the bound state field. Use
/// [`refresh_bindings`] to re-apply every binding in one call.
pub struct LabelBinding {
    pub label: Rc<RefCell<Label>>,
    pub accessor: fn(&ScreenState) -> String,
}

impl LabelBinding {
    /// Re-apply this binding from the supplied state.
    pub fn refresh(&self, state: &ScreenState) {
        self.label.borrow_mut().set_text((self.accessor)(state));
    }
}

/// QT-05g §3 — a decoded, magenta-keyed, `'static`-leaked artwork
/// buffer plus its natural dimensions.
#[derive(Clone, Copy)]
pub struct ImageArt {
    pub width: i32,
    pub height: i32,
    pub pixels: &'static [Color],
}

/// QT-05g §3 — reactive `Image`-source binding. Shows `on` when the
/// bound state is active, else `off`. `state_id` is the QML predicate
/// passed through verbatim to `Machine::is_active` (authority: derive).
pub struct PredicateBinding {
    pub image: Rc<RefCell<Image<'static>>>,
    pub state_id: &'static str,
    pub on: ImageArt,
    pub off: ImageArt,
}

impl PredicateBinding {
    /// Re-apply this binding from the supplied machine.
    pub fn refresh(&self, machine: &Machine) {
        let art = if machine.is_active(self.state_id) {
            &self.on
        } else {
            &self.off
        };
        self.image
            .borrow_mut()
            .set_pixels(art.width, art.height, art.pixels);
    }
}

/// QT-05h §3 — reactive `Image`-visibility binding driven by
/// `Machine::is_active`. `state_id` is the QML predicate passed
/// through verbatim (authority: derive).
pub struct VisibilityBinding {
    pub image: Rc<RefCell<Image<'static>>>,
    pub state_id: &'static str,
}

impl VisibilityBinding {
    /// Hide the Image when the bound state is inactive, else show it.
    pub fn refresh(&self, machine: &Machine) {
        self.image
            .borrow_mut()
            .set_hidden(!machine.is_active(self.state_id));
    }
}

/// QT-05i §3 — one arm of a chained predicate binding: the artwork
/// shown when `state_id` is the first active arm.
pub struct PredicateArm {
    pub state_id: &'static str,
    pub art: ImageArt,
}

/// QT-05i §3 — reactive `Image`-source binding driven by a chain of
/// `Machine::is_active` checks (first-true wins; `default` is the
/// resting else). Each `state_id` is the QML predicate passed through
/// verbatim (authority: derive).
pub struct PredicateChainBinding {
    pub image: Rc<RefCell<Image<'static>>>,
    pub arms: Vec<PredicateArm>,
    pub default: ImageArt,
}

impl PredicateChainBinding {
    /// Re-apply this binding: show the first active arm's artwork,
    /// else the resting default.
    pub fn refresh(&self, machine: &Machine) {
        let art = self
            .arms
            .iter()
            .find(|a| machine.is_active(a.state_id))
            .map(|a| &a.art)
            .unwrap_or(&self.default);
        self.image
            .borrow_mut()
            .set_pixels(art.width, art.height, art.pixels);
    }
}

/// QT-05k §3 — reactive Label-text binding sourced from an external
/// object property (e.g. `audioPlayer.currentPlayUrlFileName`). `key`
/// is the QML expression passed through verbatim (authority: derive);
/// the string value is supplied by a consumer resolver via
/// [`apply_external_text`]. The matching `(node tag, key)` pair is also
/// surfaced in [`EXTERNAL_TEXT_BINDINGS`] for tag-keyed consumers.
pub struct ExternalTextBinding {
    pub label: Rc<RefCell<Label>>,
    pub key: &'static str,
}

/// QT-05g §3 / QT-05h §3 / QT-05i §3 — sealed enum over the binding
/// sources reactive `refresh_bindings` knows how to drive.
pub enum Binding {
    Label(LabelBinding),
    Predicate(PredicateBinding),
    Visibility(VisibilityBinding),
    Chain(PredicateChainBinding),
    ExternalText(ExternalTextBinding),
}

struct BindingSink<'a, T> {
    values: &'a mut Vec<T>,
}

impl<'a, T> BindingSink<'a, T> {
    fn new(values: &'a mut Vec<T>) -> Self {
        Self { values }
    }

    fn push(&mut self, value: T) {
        self.values.push(value);
    }
}

/// Widget tree, screen state, state machine, and reactive bindings
/// returned by [`build_screen`].
#[rustfmt::skip]
pub type BuiltScreen = (
    WidgetNode,
    Rc<RefCell<ScreenState>>,
    Rc<RefCell<Machine>>,
    Vec<Binding>,
);

/// Build the screen widget tree at `bounds` and return it
/// alongside the `ScreenState` handle (QT-04b §3), the
/// `Rc<RefCell<Machine>>` istate (linkage v2) handle, and the
/// `Vec<Binding>` of reactive bindings (QT-05g §3). Callers
/// drive the machine via `machine.borrow_mut().step("…", …)`
/// and call `refresh_bindings` to re-apply state-predicate
/// artwork (e.g. Play↔Pause via `is_active`).
#[rustfmt::skip]
pub fn build_screen(
    bounds: Rect,
) -> BuiltScreen {
    let state = Rc::new(RefCell::new(ScreenState {
        i_row_spacing: 3,
        // QT-04b: non-literal default for `panelHeight`: height / 6 - AppConsts.i_DISPLAY_PADDING
        panel_height: 0,
        repeat_btn_item_selected: false,
        repeat_btn_top_border_visible: true,
        repeat_btn_highlight_background_when_selected: false,
        // QT-04b: non-literal default for `gradientColor`: AppConsts.cl_ITEM_COLOR
        repeat_btn_gradient_color: String::new(),
        btn_mediafunc_scan_item_selected: false,
        btn_mediafunc_scan_top_border_visible: true,
        btn_mediafunc_scan_highlight_background_when_selected: false,
        // QT-04b: non-literal default for `gradientColor`: AppConsts.cl_ITEM_COLOR
        btn_mediafunc_scan_gradient_color: String::new(),
        shape_path_i_offset: 7,
        btn_mediafunc_shuffle_item_selected: false,
        btn_mediafunc_shuffle_top_border_visible: true,
        btn_mediafunc_shuffle_highlight_background_when_selected: false,
        // QT-04b: non-literal default for `gradientColor`: AppConsts.cl_ITEM_COLOR
        btn_mediafunc_shuffle_gradient_color: String::new(),
        // QT-04b: non-literal default for `code`: getCode()
        warning_panel_code: 0,
    }));
    let machine = Rc::new(RefCell::new({ let mut m = Machine::new(); m.start(); m }));
    let mut bindings: Vec<Binding> = Vec::new();
    let mut binding_sink = BindingSink::new(&mut bindings);
    let node = build_pane(bounds, Rc::clone(&state), Rc::clone(&machine), &mut binding_sink);
    (node, state, machine, bindings)
}

/// Re-apply every QT-04e / QT-05g / QT-05h binding from the
/// current state and machine. Idempotent; safe to call after any
/// `machine.step(…)`. No-op when `bindings` is empty.
#[rustfmt::skip]
pub fn refresh_bindings(state: &Rc<RefCell<ScreenState>>, machine: &Rc<RefCell<Machine>>, bindings: &[Binding]) {
    let s = state.borrow();
    let m = machine.borrow();
    for b in bindings {
        match b {
                         Binding::Label(lb) => lb.refresh(&s),
                         Binding::Predicate(pb) => pb.refresh(&m),
                         Binding::Visibility(vb) => vb.refresh(&m),
                         Binding::Chain(cb) => cb.refresh(&m),
                         Binding::ExternalText(_) => {}
    }
    }
}

/// QT-05k §6 — apply a consumer-owned resolver to every external-text
/// binding. `resolve(key)` returns the current value for the verbatim
/// QML key (e.g. `"audioPlayer.currentPlayUrlFileName"`); `None` leaves
/// the Label unchanged. Call whenever the external source may have
/// changed (every frame, or on a data-change signal). No-op when there
/// are no external-text bindings.
pub fn apply_external_text(bindings: &[Binding], resolve: impl Fn(&str) -> Option<String>) {
    for b in bindings {
        if let Binding::ExternalText(t) = b
            && let Some(v) = resolve(t.key)
        {
            t.label.borrow_mut().set_text(v);
        }
    }
}

// Required `qt_assets` symbols (one RLE `&[u8]` blob each):
//   qt_assets::IMG_IMGBOLEROBACKGROUND  ←  Images/ImgBoleroBackground.png
//   qt_assets::IMG_IMGMUTE  ←  Images/ImgMute.png
//   qt_assets::IMG_IMGREWINDBACK_48  ←  Qml/Images/ImgRewindBack_48.png
//   qt_assets::IMG_IMGPAUSE_48  ←  Qml/Images/ImgPause_48.png
//   qt_assets::IMG_IMGPLAY_48  ←  Qml/Images/ImgPlay_48.png
//   qt_assets::IMG_IMGREWINDFORWARD_48  ←  Qml/Images/ImgRewindForward_48.png
//   qt_assets::IMG_IMGMEDIATRACKREPEAT_48  ←  Qml/Images/ImgMediaTrackRepeat_48.png
//   qt_assets::IMG_IMGMEDIAFOLDERREPEAT_48  ←  Qml/Images/ImgMediaFolderRepeat_48.png
//   qt_assets::IMG_IMGMEDIANOREPEAT_48  ←  Qml/Images/ImgMediaNoRepeat_48.png
//   qt_assets::IMG_IMGSHUFFLEON_48  ←  Qml/Images/ImgShuffleOn_48.png
//   qt_assets::IMG_IMGSHUFFLEOFF_48  ←  Qml/Images/ImgShuffleOff_48.png
/// Decode a vendored RLE asset into an owned, leaked pixel buffer and
/// wrap it in an `Image` widget (see emit-time docs above).
#[rustfmt::skip]
fn qt_image(bounds: Rect, rle: &'static [u8]) -> Rc<RefCell<dyn Widget>> {
    let (w, h, palette_bytes, stream) =
        rlvgl_decomp::parse_rle_blob(rle).expect("qt_image: malformed RLE asset");
    let palette_len = palette_bytes.len() / 2;
    let mut palette = alloc::vec![0u16; palette_len];
    for i in 0..palette_len {
        palette[i] = u16::from_le_bytes([palette_bytes[i * 2], palette_bytes[i * 2 + 1]]);
    }
    let rgba = rlvgl_decomp::decode_rgba(w as usize, h as usize, &palette, stream)
        .expect("qt_image: RLE decode failed");
    let pixels: Vec<Color> = rgba
        .chunks_exact(4)
        .map(|c| if c[0] == 0xFF && c[1] == 0x00 && c[2] == 0xFF {
            Color(0x00, 0x00, 0x00, 0x00) // magenta sentinel → transparent (RGB565 has no alpha)
        } else {
            Color(c[0], c[1], c[2], c[3])
        })
        .collect();
    let pixels: &'static [Color] = Vec::leak(pixels);
    let mut img = Image::new(bounds, w as i32, h as i32, pixels);
    // An Image paints its own pixels; the widget background MUST be
    // transparent so the default opaque-white `Style` does not bury
    // the artwork (and content drawn behind it).
    img.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    // QML's default `fillMode` is `Image.Stretch`: scale the source to
    // fill the destination bounds. `scale` is 8.8 fixed-point, so 256 =
    // 1:1; dest/src * 256 stretches source pixels across `bounds`.
    let scale_x = if w > 0 {
        ((bounds.width.max(0) as i64 * 256 / w as i64).clamp(1, 0xffff)) as u16
    } else { 256 };
    let scale_y = if h > 0 {
        ((bounds.height.max(0) as i64 * 256 / h as i64).clamp(1, 0xffff)) as u16
    } else { 256 };
    let img = img.with_blit_opts(BlitOpts { scale_x, scale_y, ..BlitOpts::default() });
    Rc::new(RefCell::new(img))
}

/// QT-05g: decode one vendored RLE asset into a leaked `ImageArt`
/// (magenta-keyed → transparent, RGB565 has no alpha).
#[rustfmt::skip]
fn qt_image_art(rle: &'static [u8]) -> ImageArt {
    let (w, h, palette_bytes, stream) =
        rlvgl_decomp::parse_rle_blob(rle).expect("qt_image_art: malformed RLE asset");
    let palette_len = palette_bytes.len() / 2;
    let mut palette = alloc::vec![0u16; palette_len];
    for i in 0..palette_len {
        palette[i] = u16::from_le_bytes([palette_bytes[i * 2], palette_bytes[i * 2 + 1]]);
    }
    let rgba = rlvgl_decomp::decode_rgba(w as usize, h as usize, &palette, stream)
        .expect("qt_image_art: RLE decode failed");
    let pixels: Vec<Color> = rgba
        .chunks_exact(4)
        .map(|c| if c[0] == 0xFF && c[1] == 0x00 && c[2] == 0xFF {
            Color(0x00, 0x00, 0x00, 0x00)
        } else {
            Color(c[0], c[1], c[2], c[3])
        })
        .collect();
    let pixels: &'static [Color] = Vec::leak(pixels);
    ImageArt { width: w as i32, height: h as i32, pixels }
}

/// QT-05g: build a predicate-bound Image. Decodes both branches, builds
/// the Image at the machine-driven branch, and returns it as a
/// `dyn Widget` plus the `Binding::Predicate` that swaps it on refresh.
#[rustfmt::skip]
fn qt_predicate_image(
    bounds: Rect,
    on_rle: &'static [u8],
    off_rle: &'static [u8],
    state_id: &'static str,
    active: bool,
) -> (Rc<RefCell<dyn Widget>>, Binding) {
    let on = qt_image_art(on_rle);
    let off = qt_image_art(off_rle);
    let cur = if active { on } else { off };
    let mut img = Image::new(bounds, cur.width, cur.height, cur.pixels);
    img.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    // QML default `Image.Stretch`: scale source → bounds (8.8 fixed-point).
    let scale_x = if cur.width > 0 {
        ((bounds.width.max(0) as i64 * 256 / cur.width as i64).clamp(1, 0xffff)) as u16
    } else { 256 };
    let scale_y = if cur.height > 0 {
        ((bounds.height.max(0) as i64 * 256 / cur.height as i64).clamp(1, 0xffff)) as u16
    } else { 256 };
    let img = img.with_blit_opts(BlitOpts { scale_x, scale_y, ..BlitOpts::default() });
    let image = Rc::new(RefCell::new(img));
    let widget: Rc<RefCell<dyn Widget>> = image.clone();
    (widget, Binding::Predicate(PredicateBinding { image, state_id, on, off }))
}

/// QT-05h: build a visibility-bound Image. Decodes the source, builds
/// the Image (initially hidden iff the bound state is inactive), and
/// returns it as a `dyn Widget` plus its `Binding::Visibility`.
#[rustfmt::skip]
fn qt_visibility_image(
    bounds: Rect,
    rle: &'static [u8],
    state_id: &'static str,
    visible: bool,
) -> (Rc<RefCell<dyn Widget>>, Binding) {
    let art = qt_image_art(rle);
    let mut img = Image::new(bounds, art.width, art.height, art.pixels);
    img.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let scale_x = if art.width > 0 {
        ((bounds.width.max(0) as i64 * 256 / art.width as i64).clamp(1, 0xffff)) as u16
    } else { 256 };
    let scale_y = if art.height > 0 {
        ((bounds.height.max(0) as i64 * 256 / art.height as i64).clamp(1, 0xffff)) as u16
    } else { 256 };
    let mut img = img.with_blit_opts(BlitOpts { scale_x, scale_y, ..BlitOpts::default() });
    img.set_hidden(!visible);
    let image = Rc::new(RefCell::new(img));
    let widget: Rc<RefCell<dyn Widget>> = image.clone();
    (widget, Binding::Visibility(VisibilityBinding { image, state_id }))
}

/// QT-05i: build a chained-predicate Image. Decodes every arm + the
/// default, builds the Image at the machine-driven arm (first active
/// wins, else default), and returns it as a `dyn Widget` plus the
/// `Binding::Chain` that swaps it on refresh.
#[rustfmt::skip]
fn qt_predicate_chain_image(
    bounds: Rect,
    arms: &[(&'static [u8], &'static str)],
    default_rle: &'static [u8],
    machine: &Machine,
) -> (Rc<RefCell<dyn Widget>>, Binding) {
    let decoded: Vec<PredicateArm> = arms
        .iter()
        .map(|(rle, state_id)| PredicateArm { state_id, art: qt_image_art(rle) })
        .collect();
    let default = qt_image_art(default_rle);
    let cur = decoded
        .iter()
        .find(|a| machine.is_active(a.state_id))
        .map(|a| a.art)
        .unwrap_or(default);
    let mut img = Image::new(bounds, cur.width, cur.height, cur.pixels);
    img.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    // QML default `Image.Stretch`: scale source → bounds (8.8 fixed-point).
    let scale_x = if cur.width > 0 {
        ((bounds.width.max(0) as i64 * 256 / cur.width as i64).clamp(1, 0xffff)) as u16
    } else { 256 };
    let scale_y = if cur.height > 0 {
        ((bounds.height.max(0) as i64 * 256 / cur.height as i64).clamp(1, 0xffff)) as u16
    } else { 256 };
    let img = img.with_blit_opts(BlitOpts { scale_x, scale_y, ..BlitOpts::default() });
    let image = Rc::new(RefCell::new(img));
    let widget: Rc<RefCell<dyn Widget>> = image.clone();
    (widget, Binding::Chain(PredicateChainBinding { image, arms: decoded, default }))
}

/// Construct a `Label` with a transparent background (QML text has
/// no fill), so it does not paint the opaque-white default `Style`.
fn qt_label(text: impl Into<String>, bounds: Rect) -> Label {
    let mut l = Label::new(text, bounds);
    l.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    l
}

// QML type: `Image` (id: `pane`)
#[rustfmt::skip]
fn build_pane(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // QT-IMG: Image source → qt_assets::IMG_IMGBOLEROBACKGROUND (Images/ImgBoleroBackground.png)
    let widget: Rc<RefCell<dyn Widget>> = qt_image(bounds, qt_assets::IMG_IMGBOLEROBACKGROUND);
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("pane"),
    };
    let child_bounds = bounds;
    node.children.push(build_pane_mouse_area(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `MouseArea` (id: `paneMouseArea`)
#[rustfmt::skip]
fn build_pane_mouse_area(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    let click_area = ClickArea::new(bounds);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(click_area));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("paneMouseArea"),
    };
    let cb_2 = Rect {
        x: bounds.x + 8,
        y: bounds.y + bounds.height - 8 - (bounds.height / 6 - 8),
        width: bounds.x + bounds.width - 8 - (bounds.x + 8),
        height: bounds.height / 6 - 8,
    };
    let cb_0 = Rect {
        x: bounds.x + 8,
        y: bounds.y + 8,
        width: bounds.x + bounds.width - 8 - (bounds.x + 8),
        height: cb_2.y - (bounds.y + 8),
    };
    let cb_1 = Rect {
        x: bounds.x,
        y: bounds.y,
        width: bounds.x + bounds.width - bounds.x,
        height: bounds.y + bounds.height - bounds.y,
    };
    node.children.push(build_content_padding_item(cb_0, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_node_3(cb_1, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_bottom_panel(cb_2, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `Item` (id: `contentPaddingItem`)
#[rustfmt::skip]
fn build_content_padding_item(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("contentPaddingItem"),
    };
    let cb_0 = Rect {
        x: bounds.x,
        y: bounds.y,
        width: bounds.x + bounds.width - bounds.x,
        height: 36,
    };
    let cb_1 = Rect {
        x: bounds.x,
        y: bounds.y + bounds.height - 10 - (bounds.height / 6 - 8),
        width: bounds.x + bounds.width - bounds.x,
        height: bounds.height / 6 - 8,
    };
    let cb_3 = Rect {
        x: bounds.x + bounds.width - 160,
        y: cb_0.y + cb_0.height,
        width: 160,
        height: 160,
    };
    let cb_2 = Rect {
        x: bounds.x,
        y: cb_3.y + cb_3.height,
        width: bounds.x + bounds.width - bounds.x,
        height: cb_1.y - (cb_3.y + cb_3.height),
    };
    let cb_4 = Rect {
        x: bounds.x + 10,
        y: cb_3.y,
        width: cb_3.x - 10 - (bounds.x + 10),
        height: cb_3.y + cb_3.height - cb_3.y,
    };
    let cb_5 = Rect {
        x: bounds.x,
        y: cb_0.y + cb_0.height,
        width: cb_3.x - bounds.x,
        height: cb_2.y - (cb_0.y + cb_0.height),
    };
    node.children.push(build_header_panel(cb_0, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_function_keys(cb_1, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_timeline(cb_2, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_image_source(cb_3, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_text_source(cb_4, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_warning_panel(cb_5, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `Item` (id: `headerPanel`)
#[rustfmt::skip]
fn build_header_panel(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("headerPanel"),
    };
    let cb_0 = Rect {
        x: bounds.x + bounds.width / 2 - bounds.width / 2,
        y: bounds.y + bounds.height / 2 - bounds.height / 2,
        width: bounds.width,
        height: bounds.height,
    };
    let cb_1 = Rect {
        x: bounds.x,
        y: bounds.y,
        width: bounds.width,
        height: bounds.height,
    };
    let cb_2 = Rect {
        x: cb_0.x - 32,
        y: bounds.y + bounds.height / 2 - 32 / 2,
        width: 32,
        height: 32,
    };
    let cb_3 = Rect {
        x: bounds.x + bounds.width - bounds.width,
        y: bounds.y + bounds.height / 2 - bounds.height / 2,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_text_time(cb_0, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_timer(cb_1, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_img_mute(cb_2, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_text_temperature(cb_3, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `Text` (id: `textTime`)
#[rustfmt::skip]
fn build_text_time(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(qt_label("", bounds)));
    WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("textTime"),
    }
}

// QML type: `Timer` (id: `timer`)
#[rustfmt::skip]
fn build_timer(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `Timer`
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("timer"),
    }
}

// QML type: `Image` (id: `imgMute`)
#[rustfmt::skip]
fn build_img_mute(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // QT-05h visibility-bound: visible → scxmlBolero.muteOn (source IMG_IMGMUTE)
    let visible = machine.borrow().is_active("muteOn");
    let (widget, __vb): (Rc<RefCell<dyn Widget>>, Binding) =
        qt_visibility_image(bounds, qt_assets::IMG_IMGMUTE, "muteOn", visible);
    bindings.push(__vb);
    WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("imgMute"),
    }
}

// QML type: `Text` (id: `textTemperature`)
#[rustfmt::skip]
fn build_text_temperature(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(qt_label("15 °C", bounds)));
    WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("textTemperature"),
    }
}

// QML type: `Item` (id: `functionKeys`)
#[rustfmt::skip]
fn build_function_keys(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("functionKeys"),
    };
    let cb_0 = Rect {
        x: bounds.x + bounds.width / 2 - 300 / 2,
        y: bounds.y,
        width: 300,
        height: bounds.y + bounds.height - bounds.y,
    };
    let cb_1 = Rect {
        x: bounds.x,
        y: bounds.y,
        width: 65,
        height: bounds.y + bounds.height - bounds.y,
    };
    let cb_2 = Rect {
        x: cb_1.x + cb_1.width + 3,
        y: bounds.y,
        width: 65,
        height: bounds.y + bounds.height - bounds.y,
    };
    let cb_3 = Rect {
        x: bounds.x + bounds.width - 65,
        y: bounds.y,
        width: 65,
        height: bounds.y + bounds.height - bounds.y,
    };
    node.children.push(build_row_buttons(cb_0, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_repeat_btn(cb_1, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_btn_mediafunc_scan(cb_2, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_btn_mediafunc_shuffle(cb_3, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `RowLayout` (id: `rowButtons`)
#[rustfmt::skip]
fn build_row_buttons(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `RowLayout`
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("rowButtons"),
    };
    let child_bounds = Rect {
        x: bounds.x,
        y: bounds.y,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_repeater_buttons(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `Repeater` (id: `repeaterButtons`)
#[rustfmt::skip]
fn build_repeater_buttons(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `Repeater`
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("repeaterButtons"),
    };
    let cb_0 = Rect {
        x: bounds.x + 75,
        y: bounds.y + bounds.height / 2 - 48 / 2,
        width: 48,
        height: 48,
    };
    let cb_1 = Rect {
        x: cb_0.x + cb_0.width + 3,
        y: bounds.y + bounds.height / 2 - 48 / 2,
        width: 48,
        height: 48,
    };
    let cb_2 = Rect {
        x: cb_1.x + cb_1.width + 3,
        y: bounds.y + bounds.height / 2 - 48 / 2,
        width: 48,
        height: 48,
    };
    node.children.push(build_rep_btn_0(cb_0, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_rep_btn_1(cb_1, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_rep_btn_2(cb_2, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `Image` (id: `__rep_btn_0`)
#[rustfmt::skip]
fn build_rep_btn_0(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // QT-IMG: Image source → qt_assets::IMG_IMGREWINDBACK_48 (Qml/Images/ImgRewindBack_48.png)
    let widget: Rc<RefCell<dyn Widget>> = qt_image(bounds, qt_assets::IMG_IMGREWINDBACK_48);
    // emitter-skipped (QT-04+): 1 signal handler(s)
    WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("__rep_btn_0"),
    }
}

// QML type: `Image` (id: `__rep_btn_1`)
#[rustfmt::skip]
fn build_rep_btn_1(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // QT-05g predicate-bound: source → scxmlBolero.mediaPlaying ? on=IMG_IMGPAUSE_48 : off=IMG_IMGPLAY_48
    let active = machine.borrow().is_active("mediaPlaying");
    let (widget, __pb): (Rc<RefCell<dyn Widget>>, Binding) =
        qt_predicate_image(bounds, qt_assets::IMG_IMGPAUSE_48, qt_assets::IMG_IMGPLAY_48, "mediaPlaying", active);
    bindings.push(__pb);
    // emitter-skipped (QT-04+): 1 signal handler(s)
    WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("__rep_btn_1"),
    }
}

// QML type: `Image` (id: `__rep_btn_2`)
#[rustfmt::skip]
fn build_rep_btn_2(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // QT-IMG: Image source → qt_assets::IMG_IMGREWINDFORWARD_48 (Qml/Images/ImgRewindForward_48.png)
    let widget: Rc<RefCell<dyn Widget>> = qt_image(bounds, qt_assets::IMG_IMGREWINDFORWARD_48);
    // emitter-skipped (QT-04+): 1 signal handler(s)
    WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("__rep_btn_2"),
    }
}

// QML type: `Button` (id: `repeatBtn`)
#[rustfmt::skip]
fn build_repeat_btn(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let mut button = Button::new("", bounds);
    button.style_mut().bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(button));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("repeatBtn"),
    };
    // QT-03c centerIn: parent (no explicit size — defaulted to parent bounds)
    let child_bounds = Rect {
        x: bounds.x,
        y: bounds.y,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_node_23(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `Image`
#[rustfmt::skip]
fn build_node_23(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // QT-05i predicate-chain-bound: source → scxmlBolero chain [mediaRepeatTrack→IMG_IMGMEDIATRACKREPEAT_48, mediaRepeatFolder→IMG_IMGMEDIAFOLDERREPEAT_48] default=IMG_IMGMEDIANOREPEAT_48
    let __arms: &[(&'static [u8], &'static str)] = &[
        (qt_assets::IMG_IMGMEDIATRACKREPEAT_48, "mediaRepeatTrack"),
        (qt_assets::IMG_IMGMEDIAFOLDERREPEAT_48, "mediaRepeatFolder"),
    ];
    let (widget, __pcb): (Rc<RefCell<dyn Widget>>, Binding) =
        qt_predicate_chain_image(bounds, __arms, qt_assets::IMG_IMGMEDIANOREPEAT_48, &machine.borrow());
    bindings.push(__pcb);
    WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    }
}

// QML type: `Button` (id: `__btn_mediafunc_scan`)
#[rustfmt::skip]
fn build_btn_mediafunc_scan(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let mut button = Button::new("", bounds);
    button.style_mut().bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(button));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("__btn_mediafunc_scan"),
    };
    let child_bounds = bounds;
    node.children.push(build_shape(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    let child_bounds = bounds;
    node.children.push(build_node_25(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `Shape` (id: `shape`)
#[rustfmt::skip]
fn build_shape(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `Shape`
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("shape"),
    };
    let child_bounds = Rect {
        x: bounds.x,
        y: bounds.y,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_shape_path(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `ShapePath` (id: `shapePath`)
#[rustfmt::skip]
fn build_shape_path(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `ShapePath`
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("shapePath"),
    };
    let child_bounds = Rect {
        x: bounds.x,
        y: bounds.y,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_node_27(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `PathLine`
#[rustfmt::skip]
fn build_node_27(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `PathLine`
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    }
}

// QML type: `Text`
#[rustfmt::skip]
fn build_node_25(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(qt_label("", bounds)));
    WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    }
}

// QML type: `Button` (id: `__btn_mediafunc_shuffle`)
#[rustfmt::skip]
fn build_btn_mediafunc_shuffle(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let mut button = Button::new("", bounds);
    button.style_mut().bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(button));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("__btn_mediafunc_shuffle"),
    };
    // QT-03c centerIn: parent (no explicit size — defaulted to parent bounds)
    let child_bounds = Rect {
        x: bounds.x,
        y: bounds.y,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_node_28(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `Image`
#[rustfmt::skip]
fn build_node_28(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // QT-05g predicate-bound: source → scxmlBolero.mediaPlayMixModeOn ? on=IMG_IMGSHUFFLEON_48 : off=IMG_IMGSHUFFLEOFF_48
    let active = machine.borrow().is_active("mediaPlayMixModeOn");
    let (widget, __pb): (Rc<RefCell<dyn Widget>>, Binding) =
        qt_predicate_image(bounds, qt_assets::IMG_IMGSHUFFLEON_48, qt_assets::IMG_IMGSHUFFLEOFF_48, "mediaPlayMixModeOn", active);
    bindings.push(__pb);
    WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    }
}

// QML type: `Item` (id: `timeline`)
#[rustfmt::skip]
fn build_timeline(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("timeline"),
    };
    let cb_0 = Rect {
        x: bounds.x,
        y: bounds.y,
        width: bounds.width,
        height: bounds.height,
    };
    let cb_1 = Rect {
        x: bounds.x + bounds.width / 2 - bounds.width / 2,
        y: bounds.y,
        width: bounds.width,
        height: bounds.y + bounds.height - bounds.y,
    };
    let cb_2 = Rect {
        x: bounds.x,
        y: bounds.y,
        width: cb_1.x - 5 - bounds.x,
        height: bounds.y + bounds.height - bounds.y,
    };
    let cb_3 = Rect {
        x: cb_1.x + cb_1.width + 5,
        y: bounds.y,
        width: bounds.x + bounds.width - (cb_1.x + cb_1.width + 5),
        height: bounds.y + bounds.height - bounds.y,
    };
    node.children.push(build_node_29(cb_0, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_time_slider(cb_1, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_text_position(cb_2, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_text_elapsed(cb_3, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `Connections`
#[rustfmt::skip]
fn build_node_29(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `Connections`
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    }
}

// QML type: `Slider` (id: `timeSlider`)
#[rustfmt::skip]
fn build_time_slider(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `Slider`
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("timeSlider"),
    }
}

// QML type: `Text` (id: `textPosition`)
#[rustfmt::skip]
fn build_text_position(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(qt_label("", bounds)));
    WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("textPosition"),
    }
}

// QML type: `Text` (id: `textElapsed`)
#[rustfmt::skip]
fn build_text_elapsed(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(qt_label("", bounds)));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("textElapsed"),
    }
}

// QML type: `Rectangle` (id: `imageSource`)
#[rustfmt::skip]
fn build_image_source(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("imageSource"),
    };
    // emitter-skipped (QT-03c+): anchors.top: parent.top
    // emitter-skipped (QT-03c+): anchors.left: parent.left
    // emitter-skipped (QT-03c+): anchors.right: parent.right
    // emitter-skipped (QT-03c+): anchors.bottom: parent.bottom
    let child_bounds = Rect {
        x: bounds.x,
        y: bounds.y,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_image(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    // emitter-skipped (QT-03c+): anchors.left: parent.left
    // emitter-skipped (QT-03c+): anchors.leftMargin: 10
    // emitter-skipped (QT-03c+): anchors.right: parent.right
    // emitter-skipped (QT-03c+): anchors.bottom: parent.bottom
    // emitter-skipped (QT-03c+): anchors.bottomMargin: 4
    let child_bounds = Rect {
        x: bounds.x,
        y: bounds.y,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_text_caption(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `Image` (id: `image`)
#[rustfmt::skip]
fn build_image(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // QT-IMG: Image with no resolvable source literal; emitting an empty transparent container
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("image"),
    }
}

// QML type: `Text` (id: `textCaption`)
#[rustfmt::skip]
fn build_text_caption(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(qt_label("", bounds)));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("textCaption"),
    }
}

// QML type: `Text` (id: `textSource`)
#[rustfmt::skip]
fn build_text_source(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // QT-05k external-text: text → audioPlayer.currentPlayUrlFileName (consumer-resolved, tag `textSource`)
    let label_handle: Rc<RefCell<Label>> = Rc::new(RefCell::new(
        qt_label("", bounds),
    ));
    let widget: Rc<RefCell<dyn Widget>> = label_handle.clone();
    bindings.push(Binding::ExternalText(ExternalTextBinding {
        label: Rc::clone(&label_handle),
        key: "audioPlayer.currentPlayUrlFileName",
    }));
    WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("textSource"),
    }
}

// QML type: `Item` (id: `warningPanel`)
#[rustfmt::skip]
fn build_warning_panel(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("warningPanel"),
    };
    let cb_0 = Rect {
        x: bounds.x,
        y: bounds.y,
        width: 100,
        height: bounds.y + bounds.height - bounds.y,
    };
    let cb_1 = Rect {
        x: cb_0.x + cb_0.width + 20,
        y: bounds.y,
        width: bounds.x + bounds.width - 10 - (cb_0.x + cb_0.width + 20),
        height: bounds.y + bounds.height - bounds.y,
    };
    node.children.push(build_busy_indicator(cb_0, Rc::clone(&state), Rc::clone(&machine), bindings));
    node.children.push(build_text_warning(cb_1, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `BusyIndicator` (id: `busyIndicator`)
#[rustfmt::skip]
fn build_busy_indicator(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `BusyIndicator`
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("busyIndicator"),
    }
}

// QML type: `Text` (id: `textWarning`)
#[rustfmt::skip]
fn build_text_warning(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // TODO QT-04e: reactive bind text (non-literal QML expression)
    let widget: Rc<RefCell<dyn Widget>> =
        Rc::new(RefCell::new(qt_label("", bounds)));
    WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("textWarning"),
    }
}

// QML type: `Rectangle`
#[rustfmt::skip]
fn build_node_3(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    let mut w = Container::new(bounds);
    // TODO QT-04e: bind color (non-literal QML expression)
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    };
    let child_bounds = bounds;
    node.children.push(build_node_37(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `MouseArea`
#[rustfmt::skip]
fn build_node_37(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    let mut click_area = ClickArea::new(bounds);
    // QT-04 body: scxmlBolero.submitEvent("Inp.App.Media.ModalOverlay.Clicked")
    click_area.set_on_click(|_b| {
        // TODO QT-04e: lower QML expression to Rust.
    });
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(click_area));
    WidgetNode {
        widget,
        children: Vec::new(),
        tag: None,
    }
}

// QML type: `Item` (id: `bottomPanel`)
#[rustfmt::skip]
fn build_bottom_panel(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("bottomPanel"),
    };
    let child_bounds = bounds;
    node.children.push(build_row_buttons_38(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `RowLayout` (id: `rowButtons`)
#[rustfmt::skip]
fn build_row_buttons_38(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `RowLayout`
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    let mut node = WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("rowButtons"),
    };
    let child_bounds = Rect {
        x: bounds.x,
        y: bounds.y,
        width: bounds.width,
        height: bounds.height,
    };
    node.children.push(build_repeater_buttons_39(child_bounds, Rc::clone(&state), Rc::clone(&machine), bindings));
    node
}

// QML type: `Repeater` (id: `repeaterButtons`)
#[rustfmt::skip]
fn build_repeater_buttons_39(
    bounds: Rect,
    state: Rc<RefCell<ScreenState>>,
    machine: Rc<RefCell<Machine>>,
    bindings: &mut BindingSink<'_, Binding>,
) -> WidgetNode {
    // emitter-fallback (QT-03b): unmapped QML type `Repeater`
    let mut w = Container::new(bounds);
    w.style.bg_color = Color(0x00, 0x00, 0x00, 0x00);
    let widget: Rc<RefCell<dyn Widget>> = Rc::new(RefCell::new(w));
    // emitter-skipped (QT-04+): 1 signal handler(s)
    WidgetNode {
        widget,
        children: Vec::new(),
        tag: Some("repeaterButtons"),
    }
}
