[package]
name = "rlvgl-api"
version = "0.2.0"
edition = "2024"
authors = ["Ira Abbott <ira@softoboros.com>"]
license = "MIT"
description = "Shared API types for rlvgl bindings"
repository = "https://github.com/softoboros/rlvgl"
homepage = "https://github.com/softoboros/rlvgl"
documentation = "https://docs.rs/rlvgl-api"

[lib]
path = "src/lib.rs"

[features]
default = []

# Target environment feature flags
micropython = []
cpython = []
cm4 = []
sim = []
