name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/iraa/rlvgl:latest
      # Start as your non-root user right away
      # options: --user ${{ vars.RLVGL_BUILDER_USER }}

    steps:
    - uses: actions/checkout@v4
    - name: Prepare build environment
      run: bash scripts/setup-ci-env.sh
    - run: rustup component add rustfmt clippy
    - run: cargo build --workspace --verbose
    - run: cargo fmt --all -- --check
    - run: cargo clippy --workspace -- -D warnings
    - run: cargo test --workspace --target x86_64-unknown-linux-gnu --verbose
    - run: RUSTDOCFLAGS="--cfg docsrs --cfg nightly" cargo +nightly doc --all-features --no-deps --target x86_64-unknown-linux-gnu
