name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: thumbv7em-none-eabihf
        profile: minimal
    - run: rustup component add rustfmt clippy
    - run: cargo build --workspace --verbose
    - run: cargo fmt --all -- --check
    - run: cargo clippy --workspace -- -D warnings
    - run: cargo test --workspace --verbose
