name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Prepare build environment
      run: bash scripts/setup-ci-env.sh
    - run: rustup component add rustfmt clippy
    - run: cargo build --workspace --verbose
    - run: cargo fmt --all -- --check
    - run: cargo clippy --workspace -- -D warnings
    - run: cargo test --workspace --target x86_64-unknown-linux-gnu --verbose
